/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 1.1 */
/* C:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -n FFTB_R2_DIT9 -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type butterfly -addr_width 9 -width 9 -rdata_width 18 -mode 0 -output_reg -pipeline 1 -e  */
/* Fri Aug 19 15:40:02 2011 */


`timescale 1 ns / 1 ps
module FFTB_R2_DIT9 (Clock, ClkEn, Reset, Twiddle_Re, Twiddle_Im, 
    DataA_Re, DataA_Im, DataB_Re, DataB_Im, ResultA_Re, ResultA_Im, 
    ResultB_Re, ResultB_Im);
    input wire Clock;
    input wire ClkEn;
    input wire Reset;
    input wire [8:0] Twiddle_Re;
    input wire [8:0] Twiddle_Im;
    input wire [8:0] DataA_Re;
    input wire [8:0] DataA_Im;
    input wire [8:0] DataB_Re;
    input wire [8:0] DataB_Im;
    output wire [17:0] ResultA_Re;
    output wire [17:0] ResultA_Im;
    output wire [17:0] ResultB_Re;
    output wire [17:0] ResultB_Im;

    wire p2_19;
    wire s0_0;
    wire s0_1;
    wire s0_2;
    wire s0_3;
    wire co0;
    wire s0_4;
    wire s0_5;
    wire co1;
    wire s0_6;
    wire s0_7;
    wire co2;
    wire s0_8;
    wire s0_9;
    wire co3;
    wire co4d;
    wire co4;
    wire s1_0;
    wire s1_1;
    wire s1_2;
    wire s1_3;
    wire co0_1;
    wire s1_4;
    wire s1_5;
    wire co1_1;
    wire s1_6;
    wire s1_7;
    wire co2_1;
    wire s1_8;
    wire s1_9;
    wire co3_1;
    wire co4_1d;
    wire co4_1;
    wire re_4x40;
    wire re_4x40_1;
    wire re_4x40_2;
    wire co0_2;
    wire re_4x40_3;
    wire re_4x40_4;
    wire co1_2;
    wire re_4x40_5;
    wire re_4x40_6;
    wire co2_2;
    wire re_4x40_7;
    wire re_4x40_8;
    wire co3_2;
    wire re_4x40_9;
    wire re_4x40_10;
    wire co4_2;
    wire re_4x40_11;
    wire re_4x40_12;
    wire co5;
    wire re_4x40_13;
    wire re_4x40_14;
    wire co6;
    wire re_4x40_15;
    wire re_4x40_16;
    wire co7;
    wire re_4x40_17;
    wire re_4x40_18;
    wire co8;
    wire co9d;
    wire co9;
    wire p1_0;
    wire p1_1;
    wire p0_0;
    wire p0_1;
    wire co0_3;
    wire p1_2;
    wire p1_3;
    wire p0_2;
    wire p0_3;
    wire co1_3;
    wire p1_4;
    wire p1_5;
    wire p0_4;
    wire p0_5;
    wire co2_3;
    wire p1_6;
    wire p1_7;
    wire p0_6;
    wire p0_7;
    wire co3_3;
    wire p1_8;
    wire p1_9;
    wire p0_8;
    wire p0_9;
    wire co4_3;
    wire p1_10;
    wire p1_11;
    wire p0_10;
    wire p0_11;
    wire co5_1;
    wire p1_12;
    wire p1_13;
    wire p0_12;
    wire p0_13;
    wire co6_1;
    wire p1_14;
    wire p1_15;
    wire p0_14;
    wire p0_15;
    wire co7_1;
    wire p1_16;
    wire p0_16;
    wire co8_1;
    wire p1_17;
    wire p0_17;
    wire im_13x40;
    wire s01_0;
    wire p2_0;
    wire im_13x40_1;
    wire im_13x40_2;
    wire co0_4;
    wire s01_1;
    wire s01_2;
    wire p2_1;
    wire p2_2;
    wire im_13x40_3;
    wire im_13x40_4;
    wire co1_4;
    wire s01_3;
    wire s01_4;
    wire p2_3;
    wire p2_4;
    wire im_13x40_5;
    wire im_13x40_6;
    wire co2_4;
    wire s01_5;
    wire s01_6;
    wire p2_5;
    wire p2_6;
    wire im_13x40_7;
    wire im_13x40_8;
    wire co3_4;
    wire s01_7;
    wire s01_8;
    wire p2_7;
    wire p2_8;
    wire im_13x40_9;
    wire im_13x40_10;
    wire co4_4;
    wire s01_9;
    wire s01_10;
    wire p2_9;
    wire p2_10;
    wire im_13x40_11;
    wire im_13x40_12;
    wire co5_2;
    wire s01_11;
    wire s01_12;
    wire p2_11;
    wire p2_12;
    wire im_13x40_13;
    wire im_13x40_14;
    wire co6_2;
    wire s01_13;
    wire s01_14;
    wire p2_13;
    wire p2_14;
    wire im_13x40_15;
    wire im_13x40_16;
    wire co7_2;
    wire s01_15;
    wire s01_16;
    wire p2_15;
    wire p2_16;
    wire im_13x40_17;
    wire im_13x40_18;
    wire co8_2;
    wire s01_17;
    wire s01_18;
    wire p2_17;
    wire p2_18;
    wire co9_1d;
    wire co9_1;
    wire add_168_326;
    wire add_168_326_1;
    wire add_168_326_2;
    wire add_168_326_3;
    wire co0_5;
    wire add_168_326_4;
    wire add_168_326_5;
    wire co1_5;
    wire add_168_326_6;
    wire add_168_326_7;
    wire co2_5;
    wire add_168_326_8;
    wire add_168_326_9;
    wire co3_5;
    wire add_168_326_10;
    wire add_168_326_11;
    wire co4_5;
    wire add_168_326_12;
    wire add_168_326_13;
    wire co5_3;
    wire add_168_326_14;
    wire add_168_326_15;
    wire co6_3;
    wire add_168_326_16;
    wire add_168_326_17;
    wire co7_3;
    wire add_168_326_18;
    wire co8_3;
    wire add_168_344;
    wire add_168_344_1;
    wire add_168_344_2;
    wire add_168_344_3;
    wire co0_6;
    wire add_168_344_4;
    wire add_168_344_5;
    wire co1_6;
    wire add_168_344_6;
    wire add_168_344_7;
    wire co2_6;
    wire add_168_344_8;
    wire add_168_344_9;
    wire co3_6;
    wire add_168_344_10;
    wire add_168_344_11;
    wire co4_6;
    wire add_168_344_12;
    wire add_168_344_13;
    wire co5_4;
    wire add_168_344_14;
    wire add_168_344_15;
    wire co6_4;
    wire add_168_344_16;
    wire add_168_344_17;
    wire co7_4;
    wire add_168_344_18;
    wire co8_4;
    wire sub_168_326;
    wire re_4x40_r;
    wire sub_168_326_1;
    wire sub_168_326_2;
    wire co0_7;
    wire re_4x40_r_1;
    wire re_4x40_r_2;
    wire sub_168_326_3;
    wire sub_168_326_4;
    wire co1_7;
    wire re_4x40_r_3;
    wire re_4x40_r_4;
    wire sub_168_326_5;
    wire sub_168_326_6;
    wire co2_7;
    wire re_4x40_r_5;
    wire re_4x40_r_6;
    wire sub_168_326_7;
    wire sub_168_326_8;
    wire co3_7;
    wire re_4x40_r_7;
    wire re_4x40_r_8;
    wire iare_r;
    wire iare_r_1;
    wire sub_168_326_9;
    wire sub_168_326_10;
    wire co4_7;
    wire re_4x40_r_9;
    wire re_4x40_r_10;
    wire iare_r_2;
    wire iare_r_3;
    wire sub_168_326_11;
    wire sub_168_326_12;
    wire co5_5;
    wire re_4x40_r_11;
    wire re_4x40_r_12;
    wire iare_r_4;
    wire iare_r_5;
    wire sub_168_326_13;
    wire sub_168_326_14;
    wire co6_5;
    wire re_4x40_r_13;
    wire re_4x40_r_14;
    wire iare_r_6;
    wire iare_r_7;
    wire sub_168_326_15;
    wire sub_168_326_16;
    wire co7_5;
    wire re_4x40_r_15;
    wire re_4x40_r_16;
    wire sub_168_326_17;
    wire sub_168_326_18;
    wire co8_5;
    wire re_4x40_r_17;
    wire iare_r_8;
    wire co9_2d;
    wire co9_2;
    wire sub_168_344;
    wire im_13x40_r;
    wire scuba_vhi;
    wire sub_168_344_1;
    wire sub_168_344_2;
    wire co0_8;
    wire im_13x40_r_1;
    wire im_13x40_r_2;
    wire sub_168_344_3;
    wire sub_168_344_4;
    wire co1_8;
    wire im_13x40_r_3;
    wire im_13x40_r_4;
    wire sub_168_344_5;
    wire sub_168_344_6;
    wire co2_8;
    wire im_13x40_r_5;
    wire im_13x40_r_6;
    wire sub_168_344_7;
    wire sub_168_344_8;
    wire co3_8;
    wire im_13x40_r_7;
    wire im_13x40_r_8;
    wire iaim_r;
    wire iaim_r_1;
    wire sub_168_344_9;
    wire sub_168_344_10;
    wire co4_8;
    wire im_13x40_r_9;
    wire im_13x40_r_10;
    wire iaim_r_2;
    wire iaim_r_3;
    wire sub_168_344_11;
    wire sub_168_344_12;
    wire co5_6;
    wire im_13x40_r_11;
    wire im_13x40_r_12;
    wire iaim_r_4;
    wire iaim_r_5;
    wire sub_168_344_13;
    wire sub_168_344_14;
    wire co6_6;
    wire im_13x40_r_13;
    wire im_13x40_r_14;
    wire iaim_r_6;
    wire iaim_r_7;
    wire sub_168_344_15;
    wire sub_168_344_16;
    wire co7_6;
    wire im_13x40_r_15;
    wire im_13x40_r_16;
    wire sub_168_344_17;
    wire sub_168_344_18;
    wire co8_6;
    wire im_13x40_r_17;
    wire iaim_r_8;
    wire co9_3d;
    wire co9_3;
    wire scuba_vlo;

    // synopsys translate_off
    defparam FF_125.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_125 (.D(DataA_Re[0]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iare_r))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_124.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_124 (.D(DataA_Re[1]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iare_r_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_123.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_123 (.D(DataA_Re[2]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iare_r_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_122.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_122 (.D(DataA_Re[3]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iare_r_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_121.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_121 (.D(DataA_Re[4]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iare_r_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_120.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_120 (.D(DataA_Re[5]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iare_r_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_119.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_119 (.D(DataA_Re[6]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iare_r_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_118.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_118 (.D(DataA_Re[7]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iare_r_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_117.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_117 (.D(DataA_Re[8]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iare_r_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_116.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_116 (.D(DataA_Im[0]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iaim_r))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_115.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_115 (.D(DataA_Im[1]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iaim_r_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_114.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_114 (.D(DataA_Im[2]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iaim_r_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_113.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_113 (.D(DataA_Im[3]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iaim_r_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_112.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_112 (.D(DataA_Im[4]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iaim_r_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_111.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_111 (.D(DataA_Im[5]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iaim_r_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_110.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_110 (.D(DataA_Im[6]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iaim_r_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_109.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_109 (.D(DataA_Im[7]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iaim_r_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_108.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_108 (.D(DataA_Im[8]), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(iaim_r_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_107.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_107 (.D(re_4x40), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_106.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_106 (.D(re_4x40_1), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_105.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_105 (.D(re_4x40_2), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_104.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_104 (.D(re_4x40_3), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_103.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_103 (.D(re_4x40_4), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_102.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_102 (.D(re_4x40_5), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_101.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_101 (.D(re_4x40_6), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_100.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_100 (.D(re_4x40_7), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_99.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_99 (.D(re_4x40_8), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_98.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_98 (.D(re_4x40_9), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_9))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_97.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_97 (.D(re_4x40_10), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_10))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_96.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_96 (.D(re_4x40_11), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_11))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_95.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_95 (.D(re_4x40_12), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_12))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_94.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_94 (.D(re_4x40_13), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_13))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_93.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_93 (.D(re_4x40_14), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_14))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_92.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_92 (.D(re_4x40_15), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_15))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_91.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_91 (.D(re_4x40_16), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_16))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_90.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_90 (.D(re_4x40_17), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(re_4x40_r_17))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_89.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_89 (.D(im_13x40), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_88.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_88 (.D(im_13x40_1), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_87.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_87 (.D(im_13x40_2), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_86.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_86 (.D(im_13x40_3), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_85.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_85 (.D(im_13x40_4), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_84.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_84 (.D(im_13x40_5), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_83.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_83 (.D(im_13x40_6), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_82.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_82 (.D(im_13x40_7), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_81.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_81 (.D(im_13x40_8), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_80.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_80 (.D(im_13x40_9), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(im_13x40_r_9))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_79.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_79 (.D(im_13x40_10), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(im_13x40_r_10))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_78.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_78 (.D(im_13x40_11), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(im_13x40_r_11))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_77.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_77 (.D(im_13x40_12), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(im_13x40_r_12))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_76.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_76 (.D(im_13x40_13), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(im_13x40_r_13))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_75.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_75 (.D(im_13x40_14), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(im_13x40_r_14))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_74.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_74 (.D(im_13x40_15), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(im_13x40_r_15))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_73.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_73 (.D(im_13x40_16), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(im_13x40_r_16))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_72.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_72 (.D(im_13x40_17), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(im_13x40_r_17))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_71.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_71 (.D(add_168_326), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_70.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_70 (.D(add_168_326_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_69.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_69 (.D(add_168_326_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_68.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_68 (.D(add_168_326_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_67.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_67 (.D(add_168_326_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_66.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_66 (.D(add_168_326_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_65.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_65 (.D(add_168_326_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_64.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_64 (.D(add_168_326_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[7]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_63.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_63 (.D(add_168_326_8), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[8]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_62.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_62 (.D(add_168_326_9), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[9]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_61.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_61 (.D(add_168_326_10), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[10]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_60.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_60 (.D(add_168_326_11), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[11]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_59.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_59 (.D(add_168_326_12), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[12]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_58.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_58 (.D(add_168_326_13), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[13]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_57.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_57 (.D(add_168_326_14), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[14]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_56.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_56 (.D(add_168_326_15), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[15]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_55.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_55 (.D(add_168_326_16), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[16]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_54.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_54 (.D(add_168_326_17), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Re[17]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_53.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_53 (.D(sub_168_326), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_52.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_52 (.D(sub_168_326_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_51.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_51 (.D(sub_168_326_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_50.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_50 (.D(sub_168_326_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_49.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_49 (.D(sub_168_326_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_48.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_48 (.D(sub_168_326_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_47.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_47 (.D(sub_168_326_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_46.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_46 (.D(sub_168_326_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[7]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_45.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_45 (.D(sub_168_326_8), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[8]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_44.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_44 (.D(sub_168_326_9), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[9]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_43.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_43 (.D(sub_168_326_10), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[10]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_42.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_42 (.D(sub_168_326_11), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[11]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_41.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_41 (.D(sub_168_326_12), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[12]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_40.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_40 (.D(sub_168_326_13), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[13]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_39.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_39 (.D(sub_168_326_14), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[14]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_38.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_38 (.D(sub_168_326_15), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[15]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_37.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_37 (.D(sub_168_326_16), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[16]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_36.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_36 (.D(sub_168_326_17), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Re[17]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_35.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_35 (.D(add_168_344), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_34.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_34 (.D(add_168_344_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_33.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_33 (.D(add_168_344_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_32.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_32 (.D(add_168_344_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_31.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_31 (.D(add_168_344_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_30.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_30 (.D(add_168_344_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_29.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_29 (.D(add_168_344_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_28.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_28 (.D(add_168_344_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[7]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_27.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_27 (.D(add_168_344_8), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[8]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_26.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_26 (.D(add_168_344_9), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[9]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_25.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_25 (.D(add_168_344_10), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[10]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_24.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_24 (.D(add_168_344_11), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[11]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_23.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_23 (.D(add_168_344_12), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[12]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_22.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_22 (.D(add_168_344_13), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[13]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_21.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_21 (.D(add_168_344_14), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[14]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_20.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_20 (.D(add_168_344_15), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[15]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_19.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_19 (.D(add_168_344_16), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[16]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_18.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_18 (.D(add_168_344_17), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultA_Im[17]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_17.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_17 (.D(sub_168_344), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_16.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_16 (.D(sub_168_344_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_15.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_15 (.D(sub_168_344_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_14.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_14 (.D(sub_168_344_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_13.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_13 (.D(sub_168_344_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_12.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_12 (.D(sub_168_344_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_11.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_11 (.D(sub_168_344_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_10.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_10 (.D(sub_168_344_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[7]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_9.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_9 (.D(sub_168_344_8), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[8]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_8.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_8 (.D(sub_168_344_9), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[9]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_7.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_7 (.D(sub_168_344_10), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[10]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_6 (.D(sub_168_344_11), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[11]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_5 (.D(sub_168_344_12), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[12]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(sub_168_344_13), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[13]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(sub_168_344_14), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[14]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(sub_168_344_15), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[15]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(sub_168_344_16), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[16]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(sub_168_344_17), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(ResultB_Im[17]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam dsp_2.GSR = "ENABLED" ;
    defparam dsp_2.REG_SIGNEDB_RST = "RST0" ;
    defparam dsp_2.REG_SIGNEDB_CE = "CE0" ;
    defparam dsp_2.REG_SIGNEDB_CLK = "NONE" ;
    defparam dsp_2.REG_SIGNEDA_RST = "RST0" ;
    defparam dsp_2.REG_SIGNEDA_CE = "CE0" ;
    defparam dsp_2.REG_SIGNEDA_CLK = "NONE" ;
    defparam dsp_2.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_2.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_2.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_2.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_2.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_2.REG_PIPELINE_CLK = "NONE" ;
    defparam dsp_2.REG_INPUTB_RST = "RST0" ;
    defparam dsp_2.REG_INPUTB_CE = "CE0" ;
    defparam dsp_2.REG_INPUTB_CLK = "NONE" ;
    defparam dsp_2.REG_INPUTA_RST = "RST0" ;
    defparam dsp_2.REG_INPUTA_CE = "CE0" ;
    defparam dsp_2.REG_INPUTA_CLK = "NONE" ;
    // synopsys translate_on
    MULT9X9B dsp_2 (.A8(Twiddle_Re[8]), .A7(Twiddle_Re[7]), .A6(Twiddle_Re[6]), 
        .A5(Twiddle_Re[5]), .A4(Twiddle_Re[4]), .A3(Twiddle_Re[3]), .A2(Twiddle_Re[2]), 
        .A1(Twiddle_Re[1]), .A0(Twiddle_Re[0]), .B8(DataB_Re[8]), .B7(DataB_Re[7]), 
        .B6(DataB_Re[6]), .B5(DataB_Re[5]), .B4(DataB_Re[4]), .B3(DataB_Re[3]), 
        .B2(DataB_Re[2]), .B1(DataB_Re[1]), .B0(DataB_Re[0]), .SIGNEDA(scuba_vhi), 
        .SIGNEDB(scuba_vhi), .SOURCEA(scuba_vlo), .SOURCEB(scuba_vlo), .CE0(scuba_vhi), 
        .CE1(scuba_vhi), .CE2(scuba_vhi), .CE3(scuba_vhi), .CLK0(scuba_vhi), 
        .CLK1(scuba_vhi), .CLK2(scuba_vhi), .CLK3(scuba_vhi), .RST0(scuba_vlo), 
        .RST1(scuba_vlo), .RST2(scuba_vlo), .RST3(scuba_vlo), .SRIA8(scuba_vlo), 
        .SRIA7(scuba_vlo), .SRIA6(scuba_vlo), .SRIA5(scuba_vlo), .SRIA4(scuba_vlo), 
        .SRIA3(scuba_vlo), .SRIA2(scuba_vlo), .SRIA1(scuba_vlo), .SRIA0(scuba_vlo), 
        .SRIB8(scuba_vlo), .SRIB7(scuba_vlo), .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), 
        .SRIB4(scuba_vlo), .SRIB3(scuba_vlo), .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), 
        .SRIB0(scuba_vlo), .SROA8(), .SROA7(), .SROA6(), .SROA5(), .SROA4(), 
        .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB8(), .SROB7(), .SROB6(), 
        .SROB5(), .SROB4(), .SROB3(), .SROB2(), .SROB1(), .SROB0(), .P17(p0_17), 
        .P16(p0_16), .P15(p0_15), .P14(p0_14), .P13(p0_13), .P12(p0_12), 
        .P11(p0_11), .P10(p0_10), .P9(p0_9), .P8(p0_8), .P7(p0_7), .P6(p0_6), 
        .P5(p0_5), .P4(p0_4), .P3(p0_3), .P2(p0_2), .P1(p0_1), .P0(p0_0))
             /* synthesis GSR="ENABLED" */
             /* synthesis REG_SIGNEDB_RST="RST0" */
             /* synthesis REG_SIGNEDB_CE="CE0" */
             /* synthesis REG_SIGNEDB_CLK="NONE" */
             /* synthesis REG_SIGNEDA_RST="RST0" */
             /* synthesis REG_SIGNEDA_CE="CE0" */
             /* synthesis REG_SIGNEDA_CLK="NONE" */
             /* synthesis REG_OUTPUT_RST="RST0" */
             /* synthesis REG_OUTPUT_CE="CE0" */
             /* synthesis REG_OUTPUT_CLK="NONE" */
             /* synthesis REG_PIPELINE_RST="RST0" */
             /* synthesis REG_PIPELINE_CE="CE0" */
             /* synthesis REG_PIPELINE_CLK="NONE" */
             /* synthesis REG_INPUTB_RST="RST0" */
             /* synthesis REG_INPUTB_CE="CE0" */
             /* synthesis REG_INPUTB_CLK="NONE" */
             /* synthesis REG_INPUTA_RST="RST0" */
             /* synthesis REG_INPUTA_CE="CE0" */
             /* synthesis REG_INPUTA_CLK="NONE" */;

    // synopsys translate_off
    defparam dsp_1.GSR = "ENABLED" ;
    defparam dsp_1.REG_SIGNEDB_RST = "RST0" ;
    defparam dsp_1.REG_SIGNEDB_CE = "CE0" ;
    defparam dsp_1.REG_SIGNEDB_CLK = "NONE" ;
    defparam dsp_1.REG_SIGNEDA_RST = "RST0" ;
    defparam dsp_1.REG_SIGNEDA_CE = "CE0" ;
    defparam dsp_1.REG_SIGNEDA_CLK = "NONE" ;
    defparam dsp_1.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_1.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_1.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_1.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_1.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_1.REG_PIPELINE_CLK = "NONE" ;
    defparam dsp_1.REG_INPUTB_RST = "RST0" ;
    defparam dsp_1.REG_INPUTB_CE = "CE0" ;
    defparam dsp_1.REG_INPUTB_CLK = "NONE" ;
    defparam dsp_1.REG_INPUTA_RST = "RST0" ;
    defparam dsp_1.REG_INPUTA_CE = "CE0" ;
    defparam dsp_1.REG_INPUTA_CLK = "NONE" ;
    // synopsys translate_on
    MULT9X9B dsp_1 (.A8(Twiddle_Im[8]), .A7(Twiddle_Im[7]), .A6(Twiddle_Im[6]), 
        .A5(Twiddle_Im[5]), .A4(Twiddle_Im[4]), .A3(Twiddle_Im[3]), .A2(Twiddle_Im[2]), 
        .A1(Twiddle_Im[1]), .A0(Twiddle_Im[0]), .B8(DataB_Im[8]), .B7(DataB_Im[7]), 
        .B6(DataB_Im[6]), .B5(DataB_Im[5]), .B4(DataB_Im[4]), .B3(DataB_Im[3]), 
        .B2(DataB_Im[2]), .B1(DataB_Im[1]), .B0(DataB_Im[0]), .SIGNEDA(scuba_vhi), 
        .SIGNEDB(scuba_vhi), .SOURCEA(scuba_vlo), .SOURCEB(scuba_vlo), .CE0(scuba_vhi), 
        .CE1(scuba_vhi), .CE2(scuba_vhi), .CE3(scuba_vhi), .CLK0(scuba_vhi), 
        .CLK1(scuba_vhi), .CLK2(scuba_vhi), .CLK3(scuba_vhi), .RST0(scuba_vlo), 
        .RST1(scuba_vlo), .RST2(scuba_vlo), .RST3(scuba_vlo), .SRIA8(scuba_vlo), 
        .SRIA7(scuba_vlo), .SRIA6(scuba_vlo), .SRIA5(scuba_vlo), .SRIA4(scuba_vlo), 
        .SRIA3(scuba_vlo), .SRIA2(scuba_vlo), .SRIA1(scuba_vlo), .SRIA0(scuba_vlo), 
        .SRIB8(scuba_vlo), .SRIB7(scuba_vlo), .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), 
        .SRIB4(scuba_vlo), .SRIB3(scuba_vlo), .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), 
        .SRIB0(scuba_vlo), .SROA8(), .SROA7(), .SROA6(), .SROA5(), .SROA4(), 
        .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB8(), .SROB7(), .SROB6(), 
        .SROB5(), .SROB4(), .SROB3(), .SROB2(), .SROB1(), .SROB0(), .P17(p1_17), 
        .P16(p1_16), .P15(p1_15), .P14(p1_14), .P13(p1_13), .P12(p1_12), 
        .P11(p1_11), .P10(p1_10), .P9(p1_9), .P8(p1_8), .P7(p1_7), .P6(p1_6), 
        .P5(p1_5), .P4(p1_4), .P3(p1_3), .P2(p1_2), .P1(p1_1), .P0(p1_0))
             /* synthesis GSR="ENABLED" */
             /* synthesis REG_SIGNEDB_RST="RST0" */
             /* synthesis REG_SIGNEDB_CE="CE0" */
             /* synthesis REG_SIGNEDB_CLK="NONE" */
             /* synthesis REG_SIGNEDA_RST="RST0" */
             /* synthesis REG_SIGNEDA_CE="CE0" */
             /* synthesis REG_SIGNEDA_CLK="NONE" */
             /* synthesis REG_OUTPUT_RST="RST0" */
             /* synthesis REG_OUTPUT_CE="CE0" */
             /* synthesis REG_OUTPUT_CLK="NONE" */
             /* synthesis REG_PIPELINE_RST="RST0" */
             /* synthesis REG_PIPELINE_CE="CE0" */
             /* synthesis REG_PIPELINE_CLK="NONE" */
             /* synthesis REG_INPUTB_RST="RST0" */
             /* synthesis REG_INPUTB_CE="CE0" */
             /* synthesis REG_INPUTB_CLK="NONE" */
             /* synthesis REG_INPUTA_RST="RST0" */
             /* synthesis REG_INPUTA_CE="CE0" */
             /* synthesis REG_INPUTA_CLK="NONE" */;

    // synopsys translate_off
    defparam dsp_0.GSR = "ENABLED" ;
    defparam dsp_0.REG_SIGNEDB_RST = "RST0" ;
    defparam dsp_0.REG_SIGNEDB_CE = "CE0" ;
    defparam dsp_0.REG_SIGNEDB_CLK = "NONE" ;
    defparam dsp_0.REG_SIGNEDA_RST = "RST0" ;
    defparam dsp_0.REG_SIGNEDA_CE = "CE0" ;
    defparam dsp_0.REG_SIGNEDA_CLK = "NONE" ;
    defparam dsp_0.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_0.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_0.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_0.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_0.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_0.REG_PIPELINE_CLK = "NONE" ;
    defparam dsp_0.REG_INPUTB_RST = "RST0" ;
    defparam dsp_0.REG_INPUTB_CE = "CE0" ;
    defparam dsp_0.REG_INPUTB_CLK = "NONE" ;
    defparam dsp_0.REG_INPUTA_RST = "RST0" ;
    defparam dsp_0.REG_INPUTA_CE = "CE0" ;
    defparam dsp_0.REG_INPUTA_CLK = "NONE" ;
    // synopsys translate_on
    MULT18X18B dsp_0 (.A17(s0_9), .A16(s0_8), .A15(s0_7), .A14(s0_6), .A13(s0_5), 
        .A12(s0_4), .A11(s0_3), .A10(s0_2), .A9(s0_1), .A8(s0_0), .A7(scuba_vlo), 
        .A6(scuba_vlo), .A5(scuba_vlo), .A4(scuba_vlo), .A3(scuba_vlo), 
        .A2(scuba_vlo), .A1(scuba_vlo), .A0(scuba_vlo), .B17(s1_9), .B16(s1_8), 
        .B15(s1_7), .B14(s1_6), .B13(s1_5), .B12(s1_4), .B11(s1_3), .B10(s1_2), 
        .B9(s1_1), .B8(s1_0), .B7(scuba_vlo), .B6(scuba_vlo), .B5(scuba_vlo), 
        .B4(scuba_vlo), .B3(scuba_vlo), .B2(scuba_vlo), .B1(scuba_vlo), 
        .B0(scuba_vlo), .SIGNEDA(scuba_vhi), .SIGNEDB(scuba_vhi), .SOURCEA(scuba_vlo), 
        .SOURCEB(scuba_vlo), .CE0(scuba_vhi), .CE1(scuba_vhi), .CE2(scuba_vhi), 
        .CE3(scuba_vhi), .CLK0(scuba_vhi), .CLK1(scuba_vhi), .CLK2(scuba_vhi), 
        .CLK3(scuba_vhi), .RST0(scuba_vlo), .RST1(scuba_vlo), .RST2(scuba_vlo), 
        .RST3(scuba_vlo), .SRIA17(scuba_vlo), .SRIA16(scuba_vlo), .SRIA15(scuba_vlo), 
        .SRIA14(scuba_vlo), .SRIA13(scuba_vlo), .SRIA12(scuba_vlo), .SRIA11(scuba_vlo), 
        .SRIA10(scuba_vlo), .SRIA9(scuba_vlo), .SRIA8(scuba_vlo), .SRIA7(scuba_vlo), 
        .SRIA6(scuba_vlo), .SRIA5(scuba_vlo), .SRIA4(scuba_vlo), .SRIA3(scuba_vlo), 
        .SRIA2(scuba_vlo), .SRIA1(scuba_vlo), .SRIA0(scuba_vlo), .SRIB17(scuba_vlo), 
        .SRIB16(scuba_vlo), .SRIB15(scuba_vlo), .SRIB14(scuba_vlo), .SRIB13(scuba_vlo), 
        .SRIB12(scuba_vlo), .SRIB11(scuba_vlo), .SRIB10(scuba_vlo), .SRIB9(scuba_vlo), 
        .SRIB8(scuba_vlo), .SRIB7(scuba_vlo), .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), 
        .SRIB4(scuba_vlo), .SRIB3(scuba_vlo), .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), 
        .SRIB0(scuba_vlo), .SROA17(), .SROA16(), .SROA15(), .SROA14(), .SROA13(), 
        .SROA12(), .SROA11(), .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), 
        .SROA5(), .SROA4(), .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), 
        .SROB16(), .SROB15(), .SROB14(), .SROB13(), .SROB12(), .SROB11(), 
        .SROB10(), .SROB9(), .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), 
        .SROB3(), .SROB2(), .SROB1(), .SROB0(), .P35(p2_19), .P34(p2_18), 
        .P33(p2_17), .P32(p2_16), .P31(p2_15), .P30(p2_14), .P29(p2_13), 
        .P28(p2_12), .P27(p2_11), .P26(p2_10), .P25(p2_9), .P24(p2_8), .P23(p2_7), 
        .P22(p2_6), .P21(p2_5), .P20(p2_4), .P19(p2_3), .P18(p2_2), .P17(p2_1), 
        .P16(p2_0), .P15(), .P14(), .P13(), .P12(), .P11(), .P10(), .P9(), 
        .P8(), .P7(), .P6(), .P5(), .P4(), .P3(), .P2(), .P1(), .P0())
             /* synthesis GSR="ENABLED" */
             /* synthesis REG_SIGNEDB_RST="RST0" */
             /* synthesis REG_SIGNEDB_CE="CE0" */
             /* synthesis REG_SIGNEDB_CLK="NONE" */
             /* synthesis REG_SIGNEDA_RST="RST0" */
             /* synthesis REG_SIGNEDA_CE="CE0" */
             /* synthesis REG_SIGNEDA_CLK="NONE" */
             /* synthesis REG_OUTPUT_RST="RST0" */
             /* synthesis REG_OUTPUT_CE="CE0" */
             /* synthesis REG_OUTPUT_CLK="NONE" */
             /* synthesis REG_PIPELINE_RST="RST0" */
             /* synthesis REG_PIPELINE_CE="CE0" */
             /* synthesis REG_PIPELINE_CLK="NONE" */
             /* synthesis REG_INPUTB_RST="RST0" */
             /* synthesis REG_INPUTB_CE="CE0" */
             /* synthesis REG_INPUTB_CLK="NONE" */
             /* synthesis REG_INPUTA_RST="RST0" */
             /* synthesis REG_INPUTA_CE="CE0" */
             /* synthesis REG_INPUTA_CLK="NONE" */;

    FADD2B mult_CitreD_CibreD_s0add_0 (.A0(Twiddle_Re[0]), .A1(Twiddle_Re[1]), 
        .B0(Twiddle_Im[0]), .B1(Twiddle_Im[1]), .CI(scuba_vlo), .COUT(co0), 
        .S0(s0_0), .S1(s0_1));

    FADD2B mult_CitreD_CibreD_s0add_1 (.A0(Twiddle_Re[2]), .A1(Twiddle_Re[3]), 
        .B0(Twiddle_Im[2]), .B1(Twiddle_Im[3]), .CI(co0), .COUT(co1), .S0(s0_2), 
        .S1(s0_3));

    FADD2B mult_CitreD_CibreD_s0add_2 (.A0(Twiddle_Re[4]), .A1(Twiddle_Re[5]), 
        .B0(Twiddle_Im[4]), .B1(Twiddle_Im[5]), .CI(co1), .COUT(co2), .S0(s0_4), 
        .S1(s0_5));

    FADD2B mult_CitreD_CibreD_s0add_3 (.A0(Twiddle_Re[6]), .A1(Twiddle_Re[7]), 
        .B0(Twiddle_Im[6]), .B1(Twiddle_Im[7]), .CI(co2), .COUT(co3), .S0(s0_6), 
        .S1(s0_7));

    FADD2B mult_CitreD_CibreD_s0add_4 (.A0(Twiddle_Re[8]), .A1(Twiddle_Re[8]), 
        .B0(Twiddle_Im[8]), .B1(Twiddle_Im[8]), .CI(co3), .COUT(co4), .S0(s0_8), 
        .S1(s0_9));

    FADD2B mult_CitreD_CibreD_s0addd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co4), .COUT(), .S0(co4d), .S1());

    FADD2B mult_CitreD_CibreD_s1add_0 (.A0(DataB_Re[0]), .A1(DataB_Re[1]), 
        .B0(DataB_Im[0]), .B1(DataB_Im[1]), .CI(scuba_vlo), .COUT(co0_1), 
        .S0(s1_0), .S1(s1_1));

    FADD2B mult_CitreD_CibreD_s1add_1 (.A0(DataB_Re[2]), .A1(DataB_Re[3]), 
        .B0(DataB_Im[2]), .B1(DataB_Im[3]), .CI(co0_1), .COUT(co1_1), .S0(s1_2), 
        .S1(s1_3));

    FADD2B mult_CitreD_CibreD_s1add_2 (.A0(DataB_Re[4]), .A1(DataB_Re[5]), 
        .B0(DataB_Im[4]), .B1(DataB_Im[5]), .CI(co1_1), .COUT(co2_1), .S0(s1_4), 
        .S1(s1_5));

    FADD2B mult_CitreD_CibreD_s1add_3 (.A0(DataB_Re[6]), .A1(DataB_Re[7]), 
        .B0(DataB_Im[6]), .B1(DataB_Im[7]), .CI(co2_1), .COUT(co3_1), .S0(s1_6), 
        .S1(s1_7));

    FADD2B mult_CitreD_CibreD_s1add_4 (.A0(DataB_Re[8]), .A1(DataB_Re[8]), 
        .B0(DataB_Im[8]), .B1(DataB_Im[8]), .CI(co3_1), .COUT(co4_1), .S0(s1_8), 
        .S1(s1_9));

    FADD2B mult_CitreD_CibreD_s1addd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co4_1), .COUT(), .S0(co4_1d), .S1());

    FSUB2B mult_CitreD_CibreD_sradd_0 (.A0(scuba_vhi), .A1(p0_0), .B0(scuba_vlo), 
        .B1(p1_0), .BI(scuba_vlo), .BOUT(co0_2), .S0(), .S1(re_4x40));

    FSUB2B mult_CitreD_CibreD_sradd_1 (.A0(p0_1), .A1(p0_2), .B0(p1_1), 
        .B1(p1_2), .BI(co0_2), .BOUT(co1_2), .S0(re_4x40_1), .S1(re_4x40_2));

    FSUB2B mult_CitreD_CibreD_sradd_2 (.A0(p0_3), .A1(p0_4), .B0(p1_3), 
        .B1(p1_4), .BI(co1_2), .BOUT(co2_2), .S0(re_4x40_3), .S1(re_4x40_4));

    FSUB2B mult_CitreD_CibreD_sradd_3 (.A0(p0_5), .A1(p0_6), .B0(p1_5), 
        .B1(p1_6), .BI(co2_2), .BOUT(co3_2), .S0(re_4x40_5), .S1(re_4x40_6));

    FSUB2B mult_CitreD_CibreD_sradd_4 (.A0(p0_7), .A1(p0_8), .B0(p1_7), 
        .B1(p1_8), .BI(co3_2), .BOUT(co4_2), .S0(re_4x40_7), .S1(re_4x40_8));

    FSUB2B mult_CitreD_CibreD_sradd_5 (.A0(p0_9), .A1(p0_10), .B0(p1_9), 
        .B1(p1_10), .BI(co4_2), .BOUT(co5), .S0(re_4x40_9), .S1(re_4x40_10));

    FSUB2B mult_CitreD_CibreD_sradd_6 (.A0(p0_11), .A1(p0_12), .B0(p1_11), 
        .B1(p1_12), .BI(co5), .BOUT(co6), .S0(re_4x40_11), .S1(re_4x40_12));

    FSUB2B mult_CitreD_CibreD_sradd_7 (.A0(p0_13), .A1(p0_14), .B0(p1_13), 
        .B1(p1_14), .BI(co6), .BOUT(co7), .S0(re_4x40_13), .S1(re_4x40_14));

    FSUB2B mult_CitreD_CibreD_sradd_8 (.A0(p0_15), .A1(p0_16), .B0(p1_15), 
        .B1(p1_16), .BI(co7), .BOUT(co8), .S0(re_4x40_15), .S1(re_4x40_16));

    FSUB2B mult_CitreD_CibreD_sradd_9 (.A0(p0_17), .A1(p0_17), .B0(p1_17), 
        .B1(p1_17), .BI(co8), .BOUT(co9), .S0(re_4x40_17), .S1(re_4x40_18));

    FADD2B mult_CitreD_CibreD_sraddd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co9), .COUT(), .S0(co9d), .S1());

    FADD2B mult_CitreD_CibreD_s01add_0 (.A0(p0_0), .A1(p0_1), .B0(p1_0), 
        .B1(p1_1), .CI(scuba_vlo), .COUT(co0_3), .S0(s01_0), .S1(s01_1));

    FADD2B mult_CitreD_CibreD_s01add_1 (.A0(p0_2), .A1(p0_3), .B0(p1_2), 
        .B1(p1_3), .CI(co0_3), .COUT(co1_3), .S0(s01_2), .S1(s01_3));

    FADD2B mult_CitreD_CibreD_s01add_2 (.A0(p0_4), .A1(p0_5), .B0(p1_4), 
        .B1(p1_5), .CI(co1_3), .COUT(co2_3), .S0(s01_4), .S1(s01_5));

    FADD2B mult_CitreD_CibreD_s01add_3 (.A0(p0_6), .A1(p0_7), .B0(p1_6), 
        .B1(p1_7), .CI(co2_3), .COUT(co3_3), .S0(s01_6), .S1(s01_7));

    FADD2B mult_CitreD_CibreD_s01add_4 (.A0(p0_8), .A1(p0_9), .B0(p1_8), 
        .B1(p1_9), .CI(co3_3), .COUT(co4_3), .S0(s01_8), .S1(s01_9));

    FADD2B mult_CitreD_CibreD_s01add_5 (.A0(p0_10), .A1(p0_11), .B0(p1_10), 
        .B1(p1_11), .CI(co4_3), .COUT(co5_1), .S0(s01_10), .S1(s01_11));

    FADD2B mult_CitreD_CibreD_s01add_6 (.A0(p0_12), .A1(p0_13), .B0(p1_12), 
        .B1(p1_13), .CI(co5_1), .COUT(co6_1), .S0(s01_12), .S1(s01_13));

    FADD2B mult_CitreD_CibreD_s01add_7 (.A0(p0_14), .A1(p0_15), .B0(p1_14), 
        .B1(p1_15), .CI(co6_1), .COUT(co7_1), .S0(s01_14), .S1(s01_15));

    FADD2B mult_CitreD_CibreD_s01add_8 (.A0(p0_16), .A1(p0_17), .B0(p1_16), 
        .B1(p1_17), .CI(co7_1), .COUT(co8_1), .S0(s01_16), .S1(s01_17));

    FADD2B mult_CitreD_CibreD_s01add_9 (.A0(p0_17), .A1(scuba_vlo), .B0(p1_17), 
        .B1(scuba_vlo), .CI(co8_1), .COUT(), .S0(s01_18), .S1());

    FSUB2B mult_CitreD_CibreD_siadd_0 (.A0(scuba_vhi), .A1(p2_0), .B0(scuba_vlo), 
        .B1(s01_0), .BI(scuba_vlo), .BOUT(co0_4), .S0(), .S1(im_13x40));

    FSUB2B mult_CitreD_CibreD_siadd_1 (.A0(p2_1), .A1(p2_2), .B0(s01_1), 
        .B1(s01_2), .BI(co0_4), .BOUT(co1_4), .S0(im_13x40_1), .S1(im_13x40_2));

    FSUB2B mult_CitreD_CibreD_siadd_2 (.A0(p2_3), .A1(p2_4), .B0(s01_3), 
        .B1(s01_4), .BI(co1_4), .BOUT(co2_4), .S0(im_13x40_3), .S1(im_13x40_4));

    FSUB2B mult_CitreD_CibreD_siadd_3 (.A0(p2_5), .A1(p2_6), .B0(s01_5), 
        .B1(s01_6), .BI(co2_4), .BOUT(co3_4), .S0(im_13x40_5), .S1(im_13x40_6));

    FSUB2B mult_CitreD_CibreD_siadd_4 (.A0(p2_7), .A1(p2_8), .B0(s01_7), 
        .B1(s01_8), .BI(co3_4), .BOUT(co4_4), .S0(im_13x40_7), .S1(im_13x40_8));

    FSUB2B mult_CitreD_CibreD_siadd_5 (.A0(p2_9), .A1(p2_10), .B0(s01_9), 
        .B1(s01_10), .BI(co4_4), .BOUT(co5_2), .S0(im_13x40_9), .S1(im_13x40_10));

    FSUB2B mult_CitreD_CibreD_siadd_6 (.A0(p2_11), .A1(p2_12), .B0(s01_11), 
        .B1(s01_12), .BI(co5_2), .BOUT(co6_2), .S0(im_13x40_11), .S1(im_13x40_12));

    FSUB2B mult_CitreD_CibreD_siadd_7 (.A0(p2_13), .A1(p2_14), .B0(s01_13), 
        .B1(s01_14), .BI(co6_2), .BOUT(co7_2), .S0(im_13x40_13), .S1(im_13x40_14));

    FSUB2B mult_CitreD_CibreD_siadd_8 (.A0(p2_15), .A1(p2_16), .B0(s01_15), 
        .B1(s01_16), .BI(co7_2), .BOUT(co8_2), .S0(im_13x40_15), .S1(im_13x40_16));

    FSUB2B mult_CitreD_CibreD_siadd_9 (.A0(p2_17), .A1(p2_18), .B0(s01_17), 
        .B1(s01_18), .BI(co8_2), .BOUT(co9_1), .S0(im_13x40_17), .S1(im_13x40_18));

    FADD2B mult_CitreD_CibreD_siaddd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co9_1), .COUT(), .S0(co9_1d), .S1());

    FADD2B fadd_168_326_0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(re_4x40_r), 
        .B1(re_4x40_r_1), .CI(scuba_vlo), .COUT(co0_5), .S0(add_168_326), 
        .S1(add_168_326_1));

    FADD2B fadd_168_326_1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(re_4x40_r_2), 
        .B1(re_4x40_r_3), .CI(co0_5), .COUT(co1_5), .S0(add_168_326_2), 
        .S1(add_168_326_3));

    FADD2B fadd_168_326_2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(re_4x40_r_4), 
        .B1(re_4x40_r_5), .CI(co1_5), .COUT(co2_5), .S0(add_168_326_4), 
        .S1(add_168_326_5));

    FADD2B fadd_168_326_3 (.A0(scuba_vlo), .A1(iare_r), .B0(re_4x40_r_6), 
        .B1(re_4x40_r_7), .CI(co2_5), .COUT(co3_5), .S0(add_168_326_6), 
        .S1(add_168_326_7));

    FADD2B fadd_168_326_4 (.A0(iare_r_1), .A1(iare_r_2), .B0(re_4x40_r_8), 
        .B1(re_4x40_r_9), .CI(co3_5), .COUT(co4_5), .S0(add_168_326_8), 
        .S1(add_168_326_9));

    FADD2B fadd_168_326_5 (.A0(iare_r_3), .A1(iare_r_4), .B0(re_4x40_r_10), 
        .B1(re_4x40_r_11), .CI(co4_5), .COUT(co5_3), .S0(add_168_326_10), 
        .S1(add_168_326_11));

    FADD2B fadd_168_326_6 (.A0(iare_r_5), .A1(iare_r_6), .B0(re_4x40_r_12), 
        .B1(re_4x40_r_13), .CI(co5_3), .COUT(co6_3), .S0(add_168_326_12), 
        .S1(add_168_326_13));

    FADD2B fadd_168_326_7 (.A0(iare_r_7), .A1(iare_r_8), .B0(re_4x40_r_14), 
        .B1(re_4x40_r_15), .CI(co6_3), .COUT(co7_3), .S0(add_168_326_14), 
        .S1(add_168_326_15));

    FADD2B fadd_168_326_8 (.A0(iare_r_8), .A1(iare_r_8), .B0(re_4x40_r_16), 
        .B1(re_4x40_r_17), .CI(co7_3), .COUT(co8_3), .S0(add_168_326_16), 
        .S1(add_168_326_17));

    FADD2B fadd_168_326_9 (.A0(iare_r_8), .A1(scuba_vlo), .B0(re_4x40_r_17), 
        .B1(scuba_vlo), .CI(co8_3), .COUT(), .S0(add_168_326_18), .S1());

    FADD2B fadd_168_344_0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(im_13x40_r), 
        .B1(im_13x40_r_1), .CI(scuba_vlo), .COUT(co0_6), .S0(add_168_344), 
        .S1(add_168_344_1));

    FADD2B fadd_168_344_1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(im_13x40_r_2), 
        .B1(im_13x40_r_3), .CI(co0_6), .COUT(co1_6), .S0(add_168_344_2), 
        .S1(add_168_344_3));

    FADD2B fadd_168_344_2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(im_13x40_r_4), 
        .B1(im_13x40_r_5), .CI(co1_6), .COUT(co2_6), .S0(add_168_344_4), 
        .S1(add_168_344_5));

    FADD2B fadd_168_344_3 (.A0(scuba_vlo), .A1(iaim_r), .B0(im_13x40_r_6), 
        .B1(im_13x40_r_7), .CI(co2_6), .COUT(co3_6), .S0(add_168_344_6), 
        .S1(add_168_344_7));

    FADD2B fadd_168_344_4 (.A0(iaim_r_1), .A1(iaim_r_2), .B0(im_13x40_r_8), 
        .B1(im_13x40_r_9), .CI(co3_6), .COUT(co4_6), .S0(add_168_344_8), 
        .S1(add_168_344_9));

    FADD2B fadd_168_344_5 (.A0(iaim_r_3), .A1(iaim_r_4), .B0(im_13x40_r_10), 
        .B1(im_13x40_r_11), .CI(co4_6), .COUT(co5_4), .S0(add_168_344_10), 
        .S1(add_168_344_11));

    FADD2B fadd_168_344_6 (.A0(iaim_r_5), .A1(iaim_r_6), .B0(im_13x40_r_12), 
        .B1(im_13x40_r_13), .CI(co5_4), .COUT(co6_4), .S0(add_168_344_12), 
        .S1(add_168_344_13));

    FADD2B fadd_168_344_7 (.A0(iaim_r_7), .A1(iaim_r_8), .B0(im_13x40_r_14), 
        .B1(im_13x40_r_15), .CI(co6_4), .COUT(co7_4), .S0(add_168_344_14), 
        .S1(add_168_344_15));

    FADD2B fadd_168_344_8 (.A0(iaim_r_8), .A1(iaim_r_8), .B0(im_13x40_r_16), 
        .B1(im_13x40_r_17), .CI(co7_4), .COUT(co8_4), .S0(add_168_344_16), 
        .S1(add_168_344_17));

    FADD2B fadd_168_344_9 (.A0(iaim_r_8), .A1(scuba_vlo), .B0(im_13x40_r_17), 
        .B1(scuba_vlo), .CI(co8_4), .COUT(), .S0(add_168_344_18), .S1());

    FSUB2B fsub_168_326_0 (.A0(scuba_vhi), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(re_4x40_r), .BI(scuba_vlo), .BOUT(co0_7), .S0(), .S1(sub_168_326));

    FSUB2B fsub_168_326_1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(re_4x40_r_1), 
        .B1(re_4x40_r_2), .BI(co0_7), .BOUT(co1_7), .S0(sub_168_326_1), 
        .S1(sub_168_326_2));

    FSUB2B fsub_168_326_2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(re_4x40_r_3), 
        .B1(re_4x40_r_4), .BI(co1_7), .BOUT(co2_7), .S0(sub_168_326_3), 
        .S1(sub_168_326_4));

    FSUB2B fsub_168_326_3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(re_4x40_r_5), 
        .B1(re_4x40_r_6), .BI(co2_7), .BOUT(co3_7), .S0(sub_168_326_5), 
        .S1(sub_168_326_6));

    FSUB2B fsub_168_326_4 (.A0(iare_r), .A1(iare_r_1), .B0(re_4x40_r_7), 
        .B1(re_4x40_r_8), .BI(co3_7), .BOUT(co4_7), .S0(sub_168_326_7), 
        .S1(sub_168_326_8));

    FSUB2B fsub_168_326_5 (.A0(iare_r_2), .A1(iare_r_3), .B0(re_4x40_r_9), 
        .B1(re_4x40_r_10), .BI(co4_7), .BOUT(co5_5), .S0(sub_168_326_9), 
        .S1(sub_168_326_10));

    FSUB2B fsub_168_326_6 (.A0(iare_r_4), .A1(iare_r_5), .B0(re_4x40_r_11), 
        .B1(re_4x40_r_12), .BI(co5_5), .BOUT(co6_5), .S0(sub_168_326_11), 
        .S1(sub_168_326_12));

    FSUB2B fsub_168_326_7 (.A0(iare_r_6), .A1(iare_r_7), .B0(re_4x40_r_13), 
        .B1(re_4x40_r_14), .BI(co6_5), .BOUT(co7_5), .S0(sub_168_326_13), 
        .S1(sub_168_326_14));

    FSUB2B fsub_168_326_8 (.A0(iare_r_8), .A1(iare_r_8), .B0(re_4x40_r_15), 
        .B1(re_4x40_r_16), .BI(co7_5), .BOUT(co8_5), .S0(sub_168_326_15), 
        .S1(sub_168_326_16));

    FSUB2B fsub_168_326_9 (.A0(iare_r_8), .A1(iare_r_8), .B0(re_4x40_r_17), 
        .B1(re_4x40_r_17), .BI(co8_5), .BOUT(co9_2), .S0(sub_168_326_17), 
        .S1(sub_168_326_18));

    FADD2B fsub_168_326d (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co9_2), .COUT(), .S0(co9_2d), .S1());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FSUB2B fsub_168_344_0 (.A0(scuba_vhi), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(im_13x40_r), .BI(scuba_vlo), .BOUT(co0_8), .S0(), .S1(sub_168_344));

    FSUB2B fsub_168_344_1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(im_13x40_r_1), 
        .B1(im_13x40_r_2), .BI(co0_8), .BOUT(co1_8), .S0(sub_168_344_1), 
        .S1(sub_168_344_2));

    FSUB2B fsub_168_344_2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(im_13x40_r_3), 
        .B1(im_13x40_r_4), .BI(co1_8), .BOUT(co2_8), .S0(sub_168_344_3), 
        .S1(sub_168_344_4));

    FSUB2B fsub_168_344_3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(im_13x40_r_5), 
        .B1(im_13x40_r_6), .BI(co2_8), .BOUT(co3_8), .S0(sub_168_344_5), 
        .S1(sub_168_344_6));

    FSUB2B fsub_168_344_4 (.A0(iaim_r), .A1(iaim_r_1), .B0(im_13x40_r_7), 
        .B1(im_13x40_r_8), .BI(co3_8), .BOUT(co4_8), .S0(sub_168_344_7), 
        .S1(sub_168_344_8));

    FSUB2B fsub_168_344_5 (.A0(iaim_r_2), .A1(iaim_r_3), .B0(im_13x40_r_9), 
        .B1(im_13x40_r_10), .BI(co4_8), .BOUT(co5_6), .S0(sub_168_344_9), 
        .S1(sub_168_344_10));

    FSUB2B fsub_168_344_6 (.A0(iaim_r_4), .A1(iaim_r_5), .B0(im_13x40_r_11), 
        .B1(im_13x40_r_12), .BI(co5_6), .BOUT(co6_6), .S0(sub_168_344_11), 
        .S1(sub_168_344_12));

    FSUB2B fsub_168_344_7 (.A0(iaim_r_6), .A1(iaim_r_7), .B0(im_13x40_r_13), 
        .B1(im_13x40_r_14), .BI(co6_6), .BOUT(co7_6), .S0(sub_168_344_13), 
        .S1(sub_168_344_14));

    FSUB2B fsub_168_344_8 (.A0(iaim_r_8), .A1(iaim_r_8), .B0(im_13x40_r_15), 
        .B1(im_13x40_r_16), .BI(co7_6), .BOUT(co8_6), .S0(sub_168_344_15), 
        .S1(sub_168_344_16));

    FSUB2B fsub_168_344_9 (.A0(iaim_r_8), .A1(iaim_r_8), .B0(im_13x40_r_17), 
        .B1(im_13x40_r_17), .BI(co8_6), .BOUT(co9_3), .S0(sub_168_344_17), 
        .S1(sub_168_344_18));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B fsub_168_344d (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co9_3), .COUT(), .S0(co9_3d), .S1());



    // exemplar begin
    // exemplar attribute FF_125 GSR ENABLED
    // exemplar attribute FF_124 GSR ENABLED
    // exemplar attribute FF_123 GSR ENABLED
    // exemplar attribute FF_122 GSR ENABLED
    // exemplar attribute FF_121 GSR ENABLED
    // exemplar attribute FF_120 GSR ENABLED
    // exemplar attribute FF_119 GSR ENABLED
    // exemplar attribute FF_118 GSR ENABLED
    // exemplar attribute FF_117 GSR ENABLED
    // exemplar attribute FF_116 GSR ENABLED
    // exemplar attribute FF_115 GSR ENABLED
    // exemplar attribute FF_114 GSR ENABLED
    // exemplar attribute FF_113 GSR ENABLED
    // exemplar attribute FF_112 GSR ENABLED
    // exemplar attribute FF_111 GSR ENABLED
    // exemplar attribute FF_110 GSR ENABLED
    // exemplar attribute FF_109 GSR ENABLED
    // exemplar attribute FF_108 GSR ENABLED
    // exemplar attribute FF_107 GSR ENABLED
    // exemplar attribute FF_106 GSR ENABLED
    // exemplar attribute FF_105 GSR ENABLED
    // exemplar attribute FF_104 GSR ENABLED
    // exemplar attribute FF_103 GSR ENABLED
    // exemplar attribute FF_102 GSR ENABLED
    // exemplar attribute FF_101 GSR ENABLED
    // exemplar attribute FF_100 GSR ENABLED
    // exemplar attribute FF_99 GSR ENABLED
    // exemplar attribute FF_98 GSR ENABLED
    // exemplar attribute FF_97 GSR ENABLED
    // exemplar attribute FF_96 GSR ENABLED
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute dsp_2 GSR ENABLED
    // exemplar attribute dsp_2 REG_SIGNEDB_RST RST0
    // exemplar attribute dsp_2 REG_SIGNEDB_CE CE0
    // exemplar attribute dsp_2 REG_SIGNEDB_CLK NONE
    // exemplar attribute dsp_2 REG_SIGNEDA_RST RST0
    // exemplar attribute dsp_2 REG_SIGNEDA_CE CE0
    // exemplar attribute dsp_2 REG_SIGNEDA_CLK NONE
    // exemplar attribute dsp_2 REG_OUTPUT_RST RST0
    // exemplar attribute dsp_2 REG_OUTPUT_CE CE0
    // exemplar attribute dsp_2 REG_OUTPUT_CLK NONE
    // exemplar attribute dsp_2 REG_PIPELINE_RST RST0
    // exemplar attribute dsp_2 REG_PIPELINE_CE CE0
    // exemplar attribute dsp_2 REG_PIPELINE_CLK NONE
    // exemplar attribute dsp_2 REG_INPUTB_RST RST0
    // exemplar attribute dsp_2 REG_INPUTB_CE CE0
    // exemplar attribute dsp_2 REG_INPUTB_CLK NONE
    // exemplar attribute dsp_2 REG_INPUTA_RST RST0
    // exemplar attribute dsp_2 REG_INPUTA_CE CE0
    // exemplar attribute dsp_2 REG_INPUTA_CLK NONE
    // exemplar attribute dsp_1 GSR ENABLED
    // exemplar attribute dsp_1 REG_SIGNEDB_RST RST0
    // exemplar attribute dsp_1 REG_SIGNEDB_CE CE0
    // exemplar attribute dsp_1 REG_SIGNEDB_CLK NONE
    // exemplar attribute dsp_1 REG_SIGNEDA_RST RST0
    // exemplar attribute dsp_1 REG_SIGNEDA_CE CE0
    // exemplar attribute dsp_1 REG_SIGNEDA_CLK NONE
    // exemplar attribute dsp_1 REG_OUTPUT_RST RST0
    // exemplar attribute dsp_1 REG_OUTPUT_CE CE0
    // exemplar attribute dsp_1 REG_OUTPUT_CLK NONE
    // exemplar attribute dsp_1 REG_PIPELINE_RST RST0
    // exemplar attribute dsp_1 REG_PIPELINE_CE CE0
    // exemplar attribute dsp_1 REG_PIPELINE_CLK NONE
    // exemplar attribute dsp_1 REG_INPUTB_RST RST0
    // exemplar attribute dsp_1 REG_INPUTB_CE CE0
    // exemplar attribute dsp_1 REG_INPUTB_CLK NONE
    // exemplar attribute dsp_1 REG_INPUTA_RST RST0
    // exemplar attribute dsp_1 REG_INPUTA_CE CE0
    // exemplar attribute dsp_1 REG_INPUTA_CLK NONE
    // exemplar attribute dsp_0 GSR ENABLED
    // exemplar attribute dsp_0 REG_SIGNEDB_RST RST0
    // exemplar attribute dsp_0 REG_SIGNEDB_CE CE0
    // exemplar attribute dsp_0 REG_SIGNEDB_CLK NONE
    // exemplar attribute dsp_0 REG_SIGNEDA_RST RST0
    // exemplar attribute dsp_0 REG_SIGNEDA_CE CE0
    // exemplar attribute dsp_0 REG_SIGNEDA_CLK NONE
    // exemplar attribute dsp_0 REG_OUTPUT_RST RST0
    // exemplar attribute dsp_0 REG_OUTPUT_CE CE0
    // exemplar attribute dsp_0 REG_OUTPUT_CLK NONE
    // exemplar attribute dsp_0 REG_PIPELINE_RST RST0
    // exemplar attribute dsp_0 REG_PIPELINE_CE CE0
    // exemplar attribute dsp_0 REG_PIPELINE_CLK NONE
    // exemplar attribute dsp_0 REG_INPUTB_RST RST0
    // exemplar attribute dsp_0 REG_INPUTB_CE CE0
    // exemplar attribute dsp_0 REG_INPUTB_CLK NONE
    // exemplar attribute dsp_0 REG_INPUTA_RST RST0
    // exemplar attribute dsp_0 REG_INPUTA_CE CE0
    // exemplar attribute dsp_0 REG_INPUTA_CLK NONE
    // exemplar end

endmodule
