/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 2.4 */
/* D:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type rom -addr_width 11 -num_rows 2048 -data_width 4 -outdata REGISTERED -memfile c:/dev/source/rb/opcode2048_400.mem -memformat bin -e  */
/* Tue Jun 14 23:20:27 2011 */


`timescale 1 ns / 1 ps
module ROM_OPCODE_DIST_2048 (Address, OutClock, OutClockEn, Reset, Q);
    input wire [10:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [3:0] Q;

    wire qdataout3_ffin;
    wire mdL0_0_7;
    wire mdL0_0_6;
    wire mdL0_0_5;
    wire mdL0_0_4;
    wire mdL0_0_3;
    wire mdL0_0_2;
    wire mdL0_0_1;
    wire mdL0_0_0;
    wire qdataout2_ffin;
    wire mdL0_1_7;
    wire mdL0_1_6;
    wire mdL0_1_5;
    wire mdL0_1_4;
    wire mdL0_1_3;
    wire mdL0_1_2;
    wire mdL0_1_1;
    wire mdL0_1_0;
    wire qdataout1_ffin;
    wire mdL0_2_7;
    wire mdL0_2_6;
    wire mdL0_2_5;
    wire mdL0_2_4;
    wire mdL0_2_3;
    wire mdL0_2_2;
    wire mdL0_2_1;
    wire mdL0_2_0;
    wire qdataout0_ffin;
    wire mdL0_3_7;
    wire mdL0_3_6;
    wire mdL0_3_5;
    wire mdL0_3_4;
    wire mdL0_3_3;
    wire mdL0_3_2;
    wire mdL0_3_1;
    wire mdL0_3_0;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam mem_0_3.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_0))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_2.initval = 256'h000000010892954D55B5B6EDDDDEF7DF7F7F7FBFFBFFEFFFFDFFFFFFEFFFFFFE ;
    // synopsys translate_on
    ROM256X1 mem_0_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_0))
             /* synthesis initval="0x000000010892954D55B5B6EDDDDEF7DF7F7F7FBFFBFFEFFFFDFFFFFFEFFFFFFE" */;

    // synopsys translate_off
    defparam mem_0_1.initval = 256'hBBDFFFFEF76D6AB2AA4A49122221082080808040040010000200000010000001 ;
    // synopsys translate_on
    ROM256X1 mem_0_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_0))
             /* synthesis initval="0xBBDFFFFEF76D6AB2AA4A49122221082080808040040010000200000010000001" */;

    // synopsys translate_off
    defparam mem_0_0.initval = 256'h4420000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_0))
             /* synthesis initval="0x4420000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_1_3.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_1))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_1_2.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_1))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_1_1.initval = 256'h4104208420842108842211108888891122448924924929294A954AAAAB56B6DB ;
    // synopsys translate_on
    ROM256X1 mem_1_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_1))
             /* synthesis initval="0x4104208420842108842211108888891122448924924929294A954AAAAB56B6DB" */;

    // synopsys translate_off
    defparam mem_1_0.initval = 256'hBEFBDF7BDF7BDEF77BDDEEEF777776EEDDBB76DB6DB6D6D6B56AB55554A94924 ;
    // synopsys translate_on
    ROM256X1 mem_1_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_1))
             /* synthesis initval="0xBEFBDF7BDF7BDEF77BDDEEEF777776EEDDBB76DB6DB6D6D6B56AB55554A94924" */;

    // synopsys translate_off
    defparam mem_2_3.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_2_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_2))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_2_2.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_2_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_2))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_2_1.initval = 256'h0200802008020100402010100804040404040404080810204081020810410410 ;
    // synopsys translate_on
    ROM256X1 mem_2_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_2))
             /* synthesis initval="0x0200802008020100402010100804040404040404080810204081020810410410" */;

    // synopsys translate_off
    defparam mem_2_0.initval = 256'hFDFF7FDFF7FDFEFFBFDFEFEFF7FBFBFBFBFBFBFBF7F7EFDFBF7EFDF7EFBEFBEF ;
    // synopsys translate_on
    ROM256X1 mem_2_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_2))
             /* synthesis initval="0xFDFF7FDFF7FDFEFFBFDFEFEFF7FBFBFBFBFBFBFBF7F7EFDFBF7EFDF7EFBEFBEF" */;

    // synopsys translate_off
    defparam mem_3_3.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_3_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_3))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_3_2.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_3_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_3))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_3_1.initval = 256'h2000400100040010004002001000800400200200200200200400400801004008 ;
    // synopsys translate_on
    ROM256X1 mem_3_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_3))
             /* synthesis initval="0x2000400100040010004002001000800400200200200200200400400801004008" */;

    // synopsys translate_off
    defparam mem_3_0.initval = 256'hDFFFBFFEFFFBFFEFFFBFFDFFEFFF7FFBFFDFFDFFDFFDFFDFFBFFBFF7FEFFBFF7 ;
    // synopsys translate_on
    ROM256X1 mem_3_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_3))
             /* synthesis initval="0xDFFFBFFEFFFBFFEFFFBFFDFFEFFF7FFBFFDFFDFFDFFDFFDFFBFFBFF7FEFFBFF7" */;

    // synopsys translate_off
    defparam mem_4_3.initval = 256'h0000000000000000000200000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_4_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_4))
             /* synthesis initval="0x0000000000000000000200000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_4_2.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_4_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_4))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_4_1.initval = 256'h0000000000000000000100008000400010001000080008000800080008001000 ;
    // synopsys translate_on
    ROM256X1 mem_4_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_4))
             /* synthesis initval="0x0000000000000000000100008000400010001000080008000800080008001000" */;

    // synopsys translate_off
    defparam mem_4_0.initval = 256'h00000000000000000000FFFF7FFFBFFFEFFFEFFFF7FFF7FFF7FFF7FFF7FFEFFF ;
    // synopsys translate_on
    ROM256X1 mem_4_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_4))
             /* synthesis initval="0x00000000000000000000FFFF7FFFBFFFEFFFEFFFF7FFF7FFF7FFF7FFF7FFEFFF" */;

    // synopsys translate_off
    defparam mem_5_3.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_5_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_5))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_5_2.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_5_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_5))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_5_1.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_5_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_5))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_5_0.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_5_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_5))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_6_3.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_6_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_6))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_6_2.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_6_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_6))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_6_1.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_6_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_6))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_6_0.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_6_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_6))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_7_3.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_7_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_7))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_7_2.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_7_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_7))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_7_1.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_7_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_7))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_7_0.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_7_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_7))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    MUX81 mux_3 (.D0(mdL0_0_0), .D1(mdL0_0_1), .D2(mdL0_0_2), .D3(mdL0_0_3), 
        .D4(mdL0_0_4), .D5(mdL0_0_5), .D6(mdL0_0_6), .D7(mdL0_0_7), .SD1(Address[8]), 
        .SD2(Address[9]), .SD3(Address[10]), .Z(qdataout3_ffin));

    MUX81 mux_2 (.D0(mdL0_1_0), .D1(mdL0_1_1), .D2(mdL0_1_2), .D3(mdL0_1_3), 
        .D4(mdL0_1_4), .D5(mdL0_1_5), .D6(mdL0_1_6), .D7(mdL0_1_7), .SD1(Address[8]), 
        .SD2(Address[9]), .SD3(Address[10]), .Z(qdataout2_ffin));

    MUX81 mux_1 (.D0(mdL0_2_0), .D1(mdL0_2_1), .D2(mdL0_2_2), .D3(mdL0_2_3), 
        .D4(mdL0_2_4), .D5(mdL0_2_5), .D6(mdL0_2_6), .D7(mdL0_2_7), .SD1(Address[8]), 
        .SD2(Address[9]), .SD3(Address[10]), .Z(qdataout1_ffin));

    MUX81 mux_0 (.D0(mdL0_3_0), .D1(mdL0_3_1), .D2(mdL0_3_2), .D3(mdL0_3_3), 
        .D4(mdL0_3_4), .D5(mdL0_3_5), .D6(mdL0_3_6), .D7(mdL0_3_7), .SD1(Address[8]), 
        .SD2(Address[9]), .SD3(Address[10]), .Z(qdataout0_ffin));



    // exemplar begin
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_3 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_2 initval 0x000000010892954D55B5B6EDDDDEF7DF7F7F7FBFFBFFEFFFFDFFFFFFEFFFFFFE
    // exemplar attribute mem_0_1 initval 0xBBDFFFFEF76D6AB2AA4A49122221082080808040040010000200000010000001
    // exemplar attribute mem_0_0 initval 0x4420000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_1_3 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_1_2 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_1_1 initval 0x4104208420842108842211108888891122448924924929294A954AAAAB56B6DB
    // exemplar attribute mem_1_0 initval 0xBEFBDF7BDF7BDEF77BDDEEEF777776EEDDBB76DB6DB6D6D6B56AB55554A94924
    // exemplar attribute mem_2_3 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_2_2 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_2_1 initval 0x0200802008020100402010100804040404040404080810204081020810410410
    // exemplar attribute mem_2_0 initval 0xFDFF7FDFF7FDFEFFBFDFEFEFF7FBFBFBFBFBFBFBF7F7EFDFBF7EFDF7EFBEFBEF
    // exemplar attribute mem_3_3 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_3_2 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_3_1 initval 0x2000400100040010004002001000800400200200200200200400400801004008
    // exemplar attribute mem_3_0 initval 0xDFFFBFFEFFFBFFEFFFBFFDFFEFFF7FFBFFDFFDFFDFFDFFDFFBFFBFF7FEFFBFF7
    // exemplar attribute mem_4_3 initval 0x0000000000000000000200000000000000000000000000000000000000000000
    // exemplar attribute mem_4_2 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_4_1 initval 0x0000000000000000000100008000400010001000080008000800080008001000
    // exemplar attribute mem_4_0 initval 0x00000000000000000000FFFF7FFFBFFFEFFFEFFFF7FFF7FFF7FFF7FFF7FFEFFF
    // exemplar attribute mem_5_3 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_5_2 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_5_1 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_5_0 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_6_3 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_6_2 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_6_1 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_6_0 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_7_3 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_7_2 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_7_1 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_7_0 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar end

endmodule
