/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 2.4 */
/* C:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type rom -addr_width 9 -num_rows 400 -data_width 5 -outdata REGISTERED -memfile c:/dev/source/rb/rom_make/fftfreq/difffreqlist_for_n4096_400d5b.mem -memformat hex -e  */
/* Sun Dec 11 17:58:55 2011 */


`timescale 1 ns / 1 ps
module DiffFreqList_for_N4096_400d5b (Address, OutClock, OutClockEn, 
    Reset, Q);
    input wire [8:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [4:0] Q;

    wire qdataout4_ffin;
    wire mdL0_0_1;
    wire mdL0_0_0;
    wire qdataout3_ffin;
    wire mdL0_1_1;
    wire mdL0_1_0;
    wire qdataout2_ffin;
    wire mdL0_2_1;
    wire mdL0_2_0;
    wire qdataout1_ffin;
    wire mdL0_3_1;
    wire mdL0_3_0;
    wire qdataout0_ffin;
    wire mdL0_4_1;
    wire mdL0_4_0;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(qdataout4_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam mem_0_4.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_0))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_3.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_0))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_2.initval = 256'h6A20000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_0))
             /* synthesis initval="0x6A20000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_1.initval = 256'h95DFFFFFFFFFEED5528840000000000000000000000000000000000000000001 ;
    // synopsys translate_on
    ROM256X1 mem_0_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_0))
             /* synthesis initval="0x95DFFFFFFFFFEED5528840000000000000000000000000000000000000000001" */;

    // synopsys translate_off
    defparam mem_0_0.initval = 256'h95DFF6D49000112AAD77BFFFFDF776DAD55554A9292492448888844210821044 ;
    // synopsys translate_on
    ROM256X1 mem_0_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_0))
             /* synthesis initval="0x95DFF6D49000112AAD77BFFFFDF776DAD55554A9292492448888844210821044" */;

    // synopsys translate_off
    defparam mem_1_4.initval = 256'h0000000000000000000000000000FFFFFFFFFFF0000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_1))
             /* synthesis initval="0x0000000000000000000000000000FFFFFFFFFFF0000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_1_3.initval = 256'h0000000000000000000000000000FFFE8000000FFFFFFFFFFFFA800000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_1))
             /* synthesis initval="0x0000000000000000000000000000FFFE8000000FFFFFFFFFFFFA800000000000" */;

    // synopsys translate_off
    defparam mem_1_2.initval = 256'h0000000000000000000000000000F8017FF0000FFFFFA00000057FFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 mem_1_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_1))
             /* synthesis initval="0x0000000000000000000000000000F8017FF0000FFFFFA00000057FFFFFFFFFFF" */;

    // synopsys translate_off
    defparam mem_1_1.initval = 256'h000000000000000000000000000007A17C0FE80FF6005FED00057FFFEA000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_1))
             /* synthesis initval="0x000000000000000000000000000007A17C0FE80FF6005FED00057FFFEA000000" */;

    // synopsys translate_off
    defparam mem_1_0.initval = 256'h0000000000000000000000000000C549234F568FA9D05D32FC857EA015FF5400 ;
    // synopsys translate_on
    ROM256X1 mem_1_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_1))
             /* synthesis initval="0x0000000000000000000000000000C549234F568FA9D05D32FC857EA015FF5400" */;

    MUX21 mux_4 (.D0(mdL0_0_0), .D1(mdL0_0_1), .SD(Address[8]), .Z(qdataout4_ffin));

    MUX21 mux_3 (.D0(mdL0_1_0), .D1(mdL0_1_1), .SD(Address[8]), .Z(qdataout3_ffin));

    MUX21 mux_2 (.D0(mdL0_2_0), .D1(mdL0_2_1), .SD(Address[8]), .Z(qdataout2_ffin));

    MUX21 mux_1 (.D0(mdL0_3_0), .D1(mdL0_3_1), .SD(Address[8]), .Z(qdataout1_ffin));

    MUX21 mux_0 (.D0(mdL0_4_0), .D1(mdL0_4_1), .SD(Address[8]), .Z(qdataout0_ffin));



    // exemplar begin
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_4 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_3 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_2 initval 0x6A20000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_1 initval 0x95DFFFFFFFFFEED5528840000000000000000000000000000000000000000001
    // exemplar attribute mem_0_0 initval 0x95DFF6D49000112AAD77BFFFFDF776DAD55554A9292492448888844210821044
    // exemplar attribute mem_1_4 initval 0x0000000000000000000000000000FFFFFFFFFFF0000000000000000000000000
    // exemplar attribute mem_1_3 initval 0x0000000000000000000000000000FFFE8000000FFFFFFFFFFFFA800000000000
    // exemplar attribute mem_1_2 initval 0x0000000000000000000000000000F8017FF0000FFFFFA00000057FFFFFFFFFFF
    // exemplar attribute mem_1_1 initval 0x000000000000000000000000000007A17C0FE80FF6005FED00057FFFEA000000
    // exemplar attribute mem_1_0 initval 0x0000000000000000000000000000C549234F568FA9D05D32FC857EA015FF5400
    // exemplar end

endmodule
