/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 2.4 */
/* D:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type rom -addr_width 9 -num_rows 512 -data_width 7 -outdata REGISTERED -memfile c:/dev/source/rb/rom_make/hannig_window/diff_quaternegativecosine.mem -memformat hex -e  */
/* Fri Jul 29 23:46:16 2011 */


`timescale 1 ns / 1 ps
module DISTROM_DIFFNCOS (Address, OutClock, OutClockEn, Reset, Q);
    input wire [8:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [6:0] Q;

    wire qdataout6_ffin;
    wire mdL0_0_1;
    wire mdL0_0_0;
    wire qdataout5_ffin;
    wire mdL0_1_1;
    wire mdL0_1_0;
    wire qdataout4_ffin;
    wire mdL0_2_1;
    wire mdL0_2_0;
    wire qdataout3_ffin;
    wire mdL0_3_1;
    wire mdL0_3_0;
    wire qdataout2_ffin;
    wire mdL0_4_1;
    wire mdL0_4_0;
    wire qdataout1_ffin;
    wire mdL0_5_1;
    wire mdL0_5_0;
    wire qdataout0_ffin;
    wire mdL0_6_1;
    wire mdL0_6_0;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_6 (.D(qdataout6_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_5 (.D(qdataout5_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(qdataout4_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam mem_0_6.initval = 256'hFFFFFFFF80000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_0))
             /* synthesis initval="0xFFFFFFFF80000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_5.initval = 256'h000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFF80000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_0))
             /* synthesis initval="0x000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFF80000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_4.initval = 256'h000000007FFFFFFFFFFFFFFF000000000000007FFFFFFFFFFFF8000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_0))
             /* synthesis initval="0x000000007FFFFFFFFFFFFFFF000000000000007FFFFFFFFFFFF8000000000000" */;

    // synopsys translate_off
    defparam mem_0_3.initval = 256'h000000007FFFFFFF40000000FFFFFFF00000007FFFFFE0000007FFFFFE000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_0))
             /* synthesis initval="0x000000007FFFFFFF40000000FFFFFFF00000007FFFFFE0000007FFFFFE000000" */;

    // synopsys translate_off
    defparam mem_0_2.initval = 256'hFFFE80007FFF4000BFFF8000FFFA000FFFE0007FFC001FFE8007FFC001FFF400 ;
    // synopsys translate_on
    ROM256X1 mem_0_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_0))
             /* synthesis initval="0xFFFE80007FFF4000BFFF8000FFFA000FFFE0007FFC001FFE8007FFC001FFF400" */;

    // synopsys translate_off
    defparam mem_0_1.initval = 256'hFE017F807F40BF40BF807F40FE05F40FE01F407E03F41FA17D07F03F81FD0BF0 ;
    // synopsys translate_on
    ROM256X1 mem_0_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_0))
             /* synthesis initval="0xFE017F807F40BF40BF807F40FE05F40FE01F407E03F41FA17D07F03F81FD0BF0" */;

    // synopsys translate_off
    defparam mem_0_0.initval = 256'hE1F170787AB9BABAB8787090E1E5AB4F1E1AB051C3891E556AA78F3C79E24A0A ;
    // synopsys translate_on
    ROM256X1 mem_0_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_0))
             /* synthesis initval="0xE1F170787AB9BABAB8787090E1E5AB4F1E1AB051C3891E556AA78F3C79E24A0A" */;

    // synopsys translate_off
    defparam mem_1_6.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 mem_1_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_1))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" */;

    // synopsys translate_off
    defparam mem_1_5.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFD20000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_1))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFFFFFFFFD20000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_1_4.initval = 256'h00000000000000000000000002DFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_1))
             /* synthesis initval="0x00000000000000000000000002DFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000" */;

    // synopsys translate_off
    defparam mem_1_3.initval = 256'h00000000000000000000000002DFFFFFFFFFFFFFFE800000000001FFFFFFFFFC ;
    // synopsys translate_on
    ROM256X1 mem_1_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_1))
             /* synthesis initval="0x00000000000000000000000002DFFFFFFFFFFFFFFE800000000001FFFFFFFFFC" */;

    // synopsys translate_off
    defparam mem_1_2.initval = 256'hFFFFFFFFFDDA48000000000002DFFFFFFFD00000017FFFFF400001FFFFE00003 ;
    // synopsys translate_on
    ROM256X1 mem_1_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_1))
             /* synthesis initval="0xFFFFFFFFFDDA48000000000002DFFFFFFFD00000017FFFFF400001FFFFE00003" */;

    // synopsys translate_off
    defparam mem_1_1.initval = 256'h000000000225B7FFFFDD480002DFFFA8002FFFA0017FF400BFE801FF401FF403 ;
    // synopsys translate_on
    ROM256X1 mem_1_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_1))
             /* synthesis initval="0x000000000225B7FFFFDD480002DFFFA8002FFFA0017FF400BFE801FF401FF403" */;

    // synopsys translate_off
    defparam mem_1_0.initval = 256'hAAA949080225B7FB5122B77202DEA057A82FD05F417A0BA0BA1781E8BC1F0B83 ;
    // synopsys translate_on
    ROM256X1 mem_1_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_1))
             /* synthesis initval="0xAAA949080225B7FB5122B77202DEA057A82FD05F417A0BA0BA1781E8BC1F0B83" */;

    MUX21 mux_6 (.D0(mdL0_0_0), .D1(mdL0_0_1), .SD(Address[8]), .Z(qdataout6_ffin));

    MUX21 mux_5 (.D0(mdL0_1_0), .D1(mdL0_1_1), .SD(Address[8]), .Z(qdataout5_ffin));

    MUX21 mux_4 (.D0(mdL0_2_0), .D1(mdL0_2_1), .SD(Address[8]), .Z(qdataout4_ffin));

    MUX21 mux_3 (.D0(mdL0_3_0), .D1(mdL0_3_1), .SD(Address[8]), .Z(qdataout3_ffin));

    MUX21 mux_2 (.D0(mdL0_4_0), .D1(mdL0_4_1), .SD(Address[8]), .Z(qdataout2_ffin));

    MUX21 mux_1 (.D0(mdL0_5_0), .D1(mdL0_5_1), .SD(Address[8]), .Z(qdataout1_ffin));

    MUX21 mux_0 (.D0(mdL0_6_0), .D1(mdL0_6_1), .SD(Address[8]), .Z(qdataout0_ffin));



    // exemplar begin
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_6 initval 0xFFFFFFFF80000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_5 initval 0x000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFF80000000000000000000000000
    // exemplar attribute mem_0_4 initval 0x000000007FFFFFFFFFFFFFFF000000000000007FFFFFFFFFFFF8000000000000
    // exemplar attribute mem_0_3 initval 0x000000007FFFFFFF40000000FFFFFFF00000007FFFFFE0000007FFFFFE000000
    // exemplar attribute mem_0_2 initval 0xFFFE80007FFF4000BFFF8000FFFA000FFFE0007FFC001FFE8007FFC001FFF400
    // exemplar attribute mem_0_1 initval 0xFE017F807F40BF40BF807F40FE05F40FE01F407E03F41FA17D07F03F81FD0BF0
    // exemplar attribute mem_0_0 initval 0xE1F170787AB9BABAB8787090E1E5AB4F1E1AB051C3891E556AA78F3C79E24A0A
    // exemplar attribute mem_1_6 initval 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    // exemplar attribute mem_1_5 initval 0xFFFFFFFFFFFFFFFFFFFFFFFFFD20000000000000000000000000000000000000
    // exemplar attribute mem_1_4 initval 0x00000000000000000000000002DFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000
    // exemplar attribute mem_1_3 initval 0x00000000000000000000000002DFFFFFFFFFFFFFFE800000000001FFFFFFFFFC
    // exemplar attribute mem_1_2 initval 0xFFFFFFFFFDDA48000000000002DFFFFFFFD00000017FFFFF400001FFFFE00003
    // exemplar attribute mem_1_1 initval 0x000000000225B7FFFFDD480002DFFFA8002FFFA0017FF400BFE801FF401FF403
    // exemplar attribute mem_1_0 initval 0xAAA949080225B7FB5122B77202DEA057A82FD05F417A0BA0BA1781E8BC1F0B83
    // exemplar end

endmodule
