/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 2.4 */
/* D:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type rom -addr_width 8 -num_rows 256 -data_width 7 -outdata REGISTERED -memfile c:/dev/source/rb/list_a.mem -memformat hex -e  */
/* Sat Jul 16 10:17:27 2011 */


`timescale 1 ns / 1 ps
module DISTROM_LIST_A_7b96d (Address, OutClock, OutClockEn, Reset, Q);
    input wire [7:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [6:0] Q;

    wire qdataout6_ffin;
    wire qdataout5_ffin;
    wire qdataout4_ffin;
    wire qdataout3_ffin;
    wire qdataout2_ffin;
    wire qdataout1_ffin;
    wire qdataout0_ffin;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_6 (.D(qdataout6_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_5 (.D(qdataout5_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(qdataout4_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam mem_0_6.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout6_ffin))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000" */;

    // synopsys translate_off
    defparam mem_0_5.initval = 256'h0000000000000000000000000000000000000000000000000FFFFFFFFFFFF000 ;
    // synopsys translate_on
    ROM256X1 mem_0_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout5_ffin))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000FFFFFFFFFFFF000" */;

    // synopsys translate_off
    defparam mem_0_4.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000000000FFFFFFFF0000FF0 ;
    // synopsys translate_on
    ROM256X1 mem_0_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout4_ffin))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000000000FFFFFFFF0000FF0" */;

    // synopsys translate_off
    defparam mem_0_3.initval = 256'hFFFFFFFFFFFFFFFFFFF80000000000001FFFFFFFFF8000000FFFFE000FF80F8C ;
    // synopsys translate_on
    ROM256X1 mem_0_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout3_ffin))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFF80000000000001FFFFFFFFF8000000FFFFE000FF80F8C" */;

    // synopsys translate_off
    defparam mem_0_2.initval = 256'hFFFFFFFFFF8000000007FFFFFFC000001FFFFF00007FFF000FFC01FC0F878C4A ;
    // synopsys translate_on
    ROM256X1 mem_0_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout2_ffin))
             /* synthesis initval="0xFFFFFFFFFF8000000007FFFFFFC000001FFFFF00007FFF000FFC01FC0F878C4A" */;

    // synopsys translate_off
    defparam mem_0_1.initval = 256'hFFFFF800007FFFF00007FFF0003FFE001FFC00FF807F80FC0F83E1C38E664B26 ;
    // synopsys translate_on
    ROM256X1 mem_0_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout1_ffin))
             /* synthesis initval="0xFFFFF800007FFFF00007FFF0003FFE001FFC00FF807F80FC0F83E1C38E664B26" */;

    // synopsys translate_off
    defparam mem_0_0.initval = 256'hFFE007FF007FE00FF007F00FE03F81F81F03E0F0787870E38E7319B369556E68 ;
    // synopsys translate_on
    ROM256X1 mem_0_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout0_ffin))
             /* synthesis initval="0xFFE007FF007FE00FF007F00FE03F81F81F03E0F0787870E38E7319B369556E68" */;



    // exemplar begin
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_6 initval 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000
    // exemplar attribute mem_0_5 initval 0x0000000000000000000000000000000000000000000000000FFFFFFFFFFFF000
    // exemplar attribute mem_0_4 initval 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000000000FFFFFFFF0000FF0
    // exemplar attribute mem_0_3 initval 0xFFFFFFFFFFFFFFFFFFF80000000000001FFFFFFFFF8000000FFFFE000FF80F8C
    // exemplar attribute mem_0_2 initval 0xFFFFFFFFFF8000000007FFFFFFC000001FFFFF00007FFF000FFC01FC0F878C4A
    // exemplar attribute mem_0_1 initval 0xFFFFF800007FFFF00007FFF0003FFE001FFC00FF807F80FC0F83E1C38E664B26
    // exemplar attribute mem_0_0 initval 0xFFE007FF007FE00FF007F00FE03F81F81F03E0F0787870E38E7319B369556E68
    // exemplar end

endmodule
