/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 2.4 */
/* C:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type rom -addr_width 9 -num_rows 400 -data_width 4 -outdata REGISTERED -memfile c:/dev/source/rb/difffreqlist_400d4b.mem -memformat hex -e  */
/* Sat Oct 29 14:58:01 2011 */


`timescale 1 ns / 1 ps
module DISTROM_DiffFreqList_400d4b (Address, OutClock, OutClockEn, Reset, 
    Q);
    input wire [8:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [3:0] Q;

    wire qdataout3_ffin;
    wire mdL0_0_1;
    wire mdL0_0_0;
    wire qdataout2_ffin;
    wire mdL0_1_1;
    wire mdL0_1_0;
    wire qdataout1_ffin;
    wire mdL0_2_1;
    wire mdL0_2_0;
    wire qdataout0_ffin;
    wire mdL0_3_1;
    wire mdL0_3_0;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam mem_0_3.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_0))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_2.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_0))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_1.initval = 256'hDDAAA92202000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_0))
             /* synthesis initval="0xDDAAA92202000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_0.initval = 256'h225556DDFDFF7F7BBB6B56AA9529492448888842108204102020201002004010 ;
    // synopsys translate_on
    ROM256X1 mem_0_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_0))
             /* synthesis initval="0x225556DDFDFF7F7BBB6B56AA9529492448888842108204102020201002004010" */;

    // synopsys translate_off
    defparam mem_1_3.initval = 256'h0000000000000000000000000000FFFFFFFFFFFA400000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_1))
             /* synthesis initval="0x0000000000000000000000000000FFFFFFFFFFFA400000000000000000000000" */;

    // synopsys translate_off
    defparam mem_1_2.initval = 256'h0000000000000000000000000000FFFF40000005BFFFFFFFFFFDB24000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_1))
             /* synthesis initval="0x0000000000000000000000000000FFFF40000005BFFFFFFFFFFDB24000000000" */;

    // synopsys translate_off
    defparam mem_1_1.initval = 256'h0000000000000000000000000000FA00BFFD0005BFFF6A0000024DBFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 mem_1_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_1))
             /* synthesis initval="0x0000000000000000000000000000FA00BFFD0005BFFF6A0000024DBFFFFFFFFF" */;

    // synopsys translate_off
    defparam mem_1_0.initval = 256'h000000000000000000000000000085D0BD02F505BD4895FED2024DBFF6D48800 ;
    // synopsys translate_on
    ROM256X1 mem_1_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_1))
             /* synthesis initval="0x000000000000000000000000000085D0BD02F505BD4895FED2024DBFF6D48800" */;

    MUX21 mux_3 (.D0(mdL0_0_0), .D1(mdL0_0_1), .SD(Address[8]), .Z(qdataout3_ffin));

    MUX21 mux_2 (.D0(mdL0_1_0), .D1(mdL0_1_1), .SD(Address[8]), .Z(qdataout2_ffin));

    MUX21 mux_1 (.D0(mdL0_2_0), .D1(mdL0_2_1), .SD(Address[8]), .Z(qdataout1_ffin));

    MUX21 mux_0 (.D0(mdL0_3_0), .D1(mdL0_3_1), .SD(Address[8]), .Z(qdataout0_ffin));



    // exemplar begin
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_3 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_2 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_1 initval 0xDDAAA92202000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_0 initval 0x225556DDFDFF7F7BBB6B56AA9529492448888842108204102020201002004010
    // exemplar attribute mem_1_3 initval 0x0000000000000000000000000000FFFFFFFFFFFA400000000000000000000000
    // exemplar attribute mem_1_2 initval 0x0000000000000000000000000000FFFF40000005BFFFFFFFFFFDB24000000000
    // exemplar attribute mem_1_1 initval 0x0000000000000000000000000000FA00BFFD0005BFFF6A0000024DBFFFFFFFFF
    // exemplar attribute mem_1_0 initval 0x000000000000000000000000000085D0BD02F505BD4895FED2024DBFF6D48800
    // exemplar end

endmodule
