/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 2.4 */
/* D:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type rom -addr_width 5 -num_rows 18 -data_width 4 -outdata REGISTERED -memfile c:/dev/source/rb/list_slope.mem -memformat hex -e  */
/* Sat Jul 16 10:17:08 2011 */


`timescale 1 ns / 1 ps
module DISTROM_LIST_SLOPE_7b20d (Address, OutClock, OutClockEn, Reset, Q);
    input wire [4:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [3:0] Q;

    wire qdataout3_ffin;
    wire qdataout2_ffin;
    wire qdataout1_ffin;
    wire qdataout0_ffin;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam mem_0_3.initval =  32'h0003FF80 ;
    // synopsys translate_on
    ROM32X1 mem_0_3 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout3_ffin))
             /* synthesis initval="0x0003FF80" */;

    // synopsys translate_off
    defparam mem_0_2.initval =  32'h0003F07E ;
    // synopsys translate_on
    ROM32X1 mem_0_2 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout2_ffin))
             /* synthesis initval="0x0003F07E" */;

    // synopsys translate_off
    defparam mem_0_1.initval =  32'h00038C71 ;
    // synopsys translate_on
    ROM32X1 mem_0_1 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout1_ffin))
             /* synthesis initval="0x00038C71" */;

    // synopsys translate_off
    defparam mem_0_0.initval =  32'h00024B6D ;
    // synopsys translate_on
    ROM32X1 mem_0_0 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout0_ffin))
             /* synthesis initval="0x00024B6D" */;



    // exemplar begin
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_3 initval 0x0003FF80
    // exemplar attribute mem_0_2 initval 0x0003F07E
    // exemplar attribute mem_0_1 initval 0x00038C71
    // exemplar attribute mem_0_0 initval 0x00024B6D
    // exemplar end

endmodule
