/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 2.4 */
/* C:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type rom -addr_width 10 -num_rows 1024 -data_width 7 -outdata REGISTERED -memfile c:/dev/source/rb/diff_quaternegcos4096n_1024d7b.mem -memformat hex -e  */
/* Wed Nov 30 16:48:26 2011 */


`timescale 1 ns / 1 ps
module DISTROM_DIFFNCOS7b1024d_for_FFT4096P (Address, OutClock, 
    OutClockEn, Reset, Q);
    input wire [9:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [6:0] Q;

    wire qdataout6_ffin;
    wire mdL0_0_3;
    wire mdL0_0_2;
    wire mdL0_0_1;
    wire mdL0_0_0;
    wire qdataout5_ffin;
    wire mdL0_1_3;
    wire mdL0_1_2;
    wire mdL0_1_1;
    wire mdL0_1_0;
    wire qdataout4_ffin;
    wire mdL0_2_3;
    wire mdL0_2_2;
    wire mdL0_2_1;
    wire mdL0_2_0;
    wire qdataout3_ffin;
    wire mdL0_3_3;
    wire mdL0_3_2;
    wire mdL0_3_1;
    wire mdL0_3_0;
    wire qdataout2_ffin;
    wire mdL0_4_3;
    wire mdL0_4_2;
    wire mdL0_4_1;
    wire mdL0_4_0;
    wire qdataout1_ffin;
    wire mdL0_5_3;
    wire mdL0_5_2;
    wire mdL0_5_1;
    wire mdL0_5_0;
    wire qdataout0_ffin;
    wire mdL0_6_3;
    wire mdL0_6_2;
    wire mdL0_6_1;
    wire mdL0_6_0;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_6 (.D(qdataout6_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_5 (.D(qdataout5_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(qdataout4_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam mem_0_6.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_0))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_5.initval = 256'hFFFFFFFFFFFE8000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_0))
             /* synthesis initval="0xFFFFFFFFFFFE8000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_4.initval = 256'h0000000000017FFFFFFFFFFFFFFFFFFFFFFFFFA8000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_0))
             /* synthesis initval="0x0000000000017FFFFFFFFFFFFFFFFFFFFFFFFFA8000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_0_3.initval = 256'h0000000000017FFFFFFFFFFFED00000000000057FFFFFFFFFFFA800000000000 ;
    // synopsys translate_on
    ROM256X1 mem_0_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_0))
             /* synthesis initval="0x0000000000017FFFFFFFFFFFED00000000000057FFFFFFFFFFFA800000000000" */;

    // synopsys translate_off
    defparam mem_0_2.initval = 256'hFFFFE80000017FFFFFB0000012FFFFFF40000057FFFFFA0000057FFFFF400000 ;
    // synopsys translate_on
    ROM256X1 mem_0_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_0))
             /* synthesis initval="0xFFFFE80000017FFFFFB0000012FFFFFF40000057FFFFFA0000057FFFFF400000" */;

    // synopsys translate_off
    defparam mem_0_1.initval = 256'hFD0017FFA8017FFA004FFF4012FFB000BFFA0057FB4005FFD0057FD800BFFA00 ;
    // synopsys translate_on
    ROM256X1 mem_0_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_0))
             /* synthesis initval="0xFD0017FFA8017FFA004FFF4012FFB000BFFA0057FB4005FFD0057FD800BFFA00" */;

    // synopsys translate_off
    defparam mem_0_0.initval = 256'h82F517E856A17D05F24FA0BD52EA4FA0BD05F4574CBA05D02EA57527D0BE85F4 ;
    // synopsys translate_on
    ROM256X1 mem_0_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_0))
             /* synthesis initval="0x82F517E856A17D05F24FA0BD52EA4FA0BD05F4574CBA05D02EA57527D0BE85F4" */;

    // synopsys translate_off
    defparam mem_1_6.initval = 256'hFFFFFFFFFFFFFFFFA40000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_1))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFA40000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_1_5.initval = 256'h00000000000000005BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 mem_1_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_1))
             /* synthesis initval="0x00000000000000005BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" */;

    // synopsys translate_off
    defparam mem_1_4.initval = 256'h00000000000000005BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD0000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_1_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_1))
             /* synthesis initval="0x00000000000000005BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD0000000000000000" */;

    // synopsys translate_off
    defparam mem_1_3.initval = 256'h00000000000000005BFFFFFFFFFFFFFFD000000000000002FFFFFFFFFFFFFD80 ;
    // synopsys translate_on
    ROM256X1 mem_1_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_1))
             /* synthesis initval="0x00000000000000005BFFFFFFFFFFFFFFD000000000000002FFFFFFFFFFFFFD80" */;

    // synopsys translate_off
    defparam mem_1_2.initval = 256'hFFFFFFFD400000005BFFFFFFD00000002FFFFFFFA0000002FFFFFFB40000027F ;
    // synopsys translate_on
    ROM256X1 mem_1_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_1))
             /* synthesis initval="0xFFFFFFFD400000005BFFFFFFD00000002FFFFFFFA0000002FFFFFFB40000027F" */;

    // synopsys translate_off
    defparam mem_1_1.initval = 256'hFFFA8002BFFEC0005BFFC8002FFFD0002FFFC8005FFD8002FFEC004BFFD0027F ;
    // synopsys translate_on
    ROM256X1 mem_1_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_1))
             /* synthesis initval="0xFFFA8002BFFEC0005BFFC8002FFFD0002FFFC8005FFD8002FFEC004BFFD0027F" */;

    // synopsys translate_off
    defparam mem_1_0.initval = 256'hEA057682BEA13FA05AD037A82FD02FD02FA036C05EA27E82FA93F94BD02F4A7E ;
    // synopsys translate_on
    ROM256X1 mem_1_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_1))
             /* synthesis initval="0xEA057682BEA13FA05AD037A82FD02FD02FA036C05EA27E82FA93F94BD02F4A7E" */;

    // synopsys translate_off
    defparam mem_2_6.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 mem_2_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_2))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" */;

    // synopsys translate_off
    defparam mem_2_5.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_2_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_2))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam mem_2_4.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDA00000000000000000000 ;
    // synopsys translate_on
    ROM256X1 mem_2_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_2))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDA00000000000000000000" */;

    // synopsys translate_off
    defparam mem_2_3.initval = 256'hFFFFFFFFFFFFFFFFFFFB200000000000000000000025FFFFFFFFFFFFFFFFFFB4 ;
    // synopsys translate_on
    ROM256X1 mem_2_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_2))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFFB200000000000000000000025FFFFFFFFFFFFFFFFFFB4" */;

    // synopsys translate_off
    defparam mem_2_2.initval = 256'hFFFFDA40000000000004DFFFFFFFFFFD500000000025FFFFFFFFFA200000004B ;
    // synopsys translate_on
    ROM256X1 mem_2_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_2))
             /* synthesis initval="0xFFFFDA40000000000004DFFFFFFFFFFD500000000025FFFFFFFFFA200000004B" */;

    // synopsys translate_off
    defparam mem_2_1.initval = 256'h000025BFFFFF6A000004DFFFF7440002AFFFFD400025FFFF500005DFFF50004B ;
    // synopsys translate_on
    ROM256X1 mem_2_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_2))
             /* synthesis initval="0x000025BFFFFF6A000004DFFFF7440002AFFFFD400025FFFF500005DFFF50004B" */;

    // synopsys translate_off
    defparam mem_2_0.initval = 256'h752025BFEA4095FED004DFB448BB7482AFB402BF6425FD40AFD805D680AF644B ;
    // synopsys translate_on
    ROM256X1 mem_2_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_2))
             /* synthesis initval="0x752025BFEA4095FED004DFB448BB7482AFB402BF6425FD40AFD805D680AF644B" */;

    // synopsys translate_off
    defparam mem_3_6.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 mem_3_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_3))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" */;

    // synopsys translate_off
    defparam mem_3_5.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBEAA10000000000 ;
    // synopsys translate_on
    ROM256X1 mem_3_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_3))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBEAA10000000000" */;

    // synopsys translate_off
    defparam mem_3_4.initval = 256'h00000000000000000000000000000000000000000000000004155EFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 mem_3_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_3))
             /* synthesis initval="0x00000000000000000000000000000000000000000000000004155EFFFFFFFFFF" */;

    // synopsys translate_off
    defparam mem_3_3.initval = 256'h00000000000000000000000000000000000000000000000004155EFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 mem_3_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_3))
             /* synthesis initval="0x00000000000000000000000000000000000000000000000004155EFFFFFFFFFF" */;

    // synopsys translate_off
    defparam mem_3_2.initval = 256'hFFFFFFFFFFFFFFFFFF7EED6A92200000000000000000000004155EFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 mem_3_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_3))
             /* synthesis initval="0xFFFFFFFFFFFFFFFFFF7EED6A92200000000000000000000004155EFFFFFFFFFF" */;

    // synopsys translate_off
    defparam mem_3_1.initval = 256'h0000000000000000008112956DDFFFFFFFFFFF755200000004155EFFFFFFD510 ;
    // synopsys translate_on
    ROM256X1 mem_3_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_3))
             /* synthesis initval="0x0000000000000000008112956DDFFFFFFFFFFF755200000004155EFFFFFFD510" */;

    // synopsys translate_off
    defparam mem_3_0.initval = 256'hAAAAAAA549244204008112956DDFFFBAD288008AADFFF5A424155EDED2002AEF ;
    // synopsys translate_on
    ROM256X1 mem_3_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_3))
             /* synthesis initval="0xAAAAAAA549244204008112956DDFFFBAD288008AADFFF5A424155EDED2002AEF" */;

    MUX41 mux_6 (.D0(mdL0_0_0), .D1(mdL0_0_1), .D2(mdL0_0_2), .D3(mdL0_0_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout6_ffin));

    MUX41 mux_5 (.D0(mdL0_1_0), .D1(mdL0_1_1), .D2(mdL0_1_2), .D3(mdL0_1_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout5_ffin));

    MUX41 mux_4 (.D0(mdL0_2_0), .D1(mdL0_2_1), .D2(mdL0_2_2), .D3(mdL0_2_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout4_ffin));

    MUX41 mux_3 (.D0(mdL0_3_0), .D1(mdL0_3_1), .D2(mdL0_3_2), .D3(mdL0_3_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout3_ffin));

    MUX41 mux_2 (.D0(mdL0_4_0), .D1(mdL0_4_1), .D2(mdL0_4_2), .D3(mdL0_4_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout2_ffin));

    MUX41 mux_1 (.D0(mdL0_5_0), .D1(mdL0_5_1), .D2(mdL0_5_2), .D3(mdL0_5_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout1_ffin));

    MUX41 mux_0 (.D0(mdL0_6_0), .D1(mdL0_6_1), .D2(mdL0_6_2), .D3(mdL0_6_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout0_ffin));



    // exemplar begin
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_6 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_5 initval 0xFFFFFFFFFFFE8000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_0_4 initval 0x0000000000017FFFFFFFFFFFFFFFFFFFFFFFFFA8000000000000000000000000
    // exemplar attribute mem_0_3 initval 0x0000000000017FFFFFFFFFFFED00000000000057FFFFFFFFFFFA800000000000
    // exemplar attribute mem_0_2 initval 0xFFFFE80000017FFFFFB0000012FFFFFF40000057FFFFFA0000057FFFFF400000
    // exemplar attribute mem_0_1 initval 0xFD0017FFA8017FFA004FFF4012FFB000BFFA0057FB4005FFD0057FD800BFFA00
    // exemplar attribute mem_0_0 initval 0x82F517E856A17D05F24FA0BD52EA4FA0BD05F4574CBA05D02EA57527D0BE85F4
    // exemplar attribute mem_1_6 initval 0xFFFFFFFFFFFFFFFFA40000000000000000000000000000000000000000000000
    // exemplar attribute mem_1_5 initval 0x00000000000000005BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    // exemplar attribute mem_1_4 initval 0x00000000000000005BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD0000000000000000
    // exemplar attribute mem_1_3 initval 0x00000000000000005BFFFFFFFFFFFFFFD000000000000002FFFFFFFFFFFFFD80
    // exemplar attribute mem_1_2 initval 0xFFFFFFFD400000005BFFFFFFD00000002FFFFFFFA0000002FFFFFFB40000027F
    // exemplar attribute mem_1_1 initval 0xFFFA8002BFFEC0005BFFC8002FFFD0002FFFC8005FFD8002FFEC004BFFD0027F
    // exemplar attribute mem_1_0 initval 0xEA057682BEA13FA05AD037A82FD02FD02FA036C05EA27E82FA93F94BD02F4A7E
    // exemplar attribute mem_2_6 initval 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    // exemplar attribute mem_2_5 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute mem_2_4 initval 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDA00000000000000000000
    // exemplar attribute mem_2_3 initval 0xFFFFFFFFFFFFFFFFFFFB200000000000000000000025FFFFFFFFFFFFFFFFFFB4
    // exemplar attribute mem_2_2 initval 0xFFFFDA40000000000004DFFFFFFFFFFD500000000025FFFFFFFFFA200000004B
    // exemplar attribute mem_2_1 initval 0x000025BFFFFF6A000004DFFFF7440002AFFFFD400025FFFF500005DFFF50004B
    // exemplar attribute mem_2_0 initval 0x752025BFEA4095FED004DFB448BB7482AFB402BF6425FD40AFD805D680AF644B
    // exemplar attribute mem_3_6 initval 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    // exemplar attribute mem_3_5 initval 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBEAA10000000000
    // exemplar attribute mem_3_4 initval 0x00000000000000000000000000000000000000000000000004155EFFFFFFFFFF
    // exemplar attribute mem_3_3 initval 0x00000000000000000000000000000000000000000000000004155EFFFFFFFFFF
    // exemplar attribute mem_3_2 initval 0xFFFFFFFFFFFFFFFFFF7EED6A92200000000000000000000004155EFFFFFFFFFF
    // exemplar attribute mem_3_1 initval 0x0000000000000000008112956DDFFFFFFFFFFF755200000004155EFFFFFFD510
    // exemplar attribute mem_3_0 initval 0xAAAAAAA549244204008112956DDFFFBAD288008AADFFF5A424155EDED2002AEF
    // exemplar end

endmodule
