/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 6.1 */
/* C:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type bram -wp 10 -rp 0011 -rdata_width 36 -data_width 36 -num_rows 16 -outdata REGISTERED -resetmode SYNC -cascade -1 -e  */
/* Wed Aug 10 15:32:34 2011 */


`timescale 1 ns / 1 ps
module DPRAM16d_36b (WrAddress, RdAddress, Data, WE, RdClock, RdClockEn, 
    Reset, WrClock, WrClockEn, Q);
    input wire [3:0] WrAddress;
    input wire [3:0] RdAddress;
    input wire [35:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [35:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam DPRAM16d_36b_0_0_0.CSDECODE_R =  3'b000 ;
    defparam DPRAM16d_36b_0_0_0.CSDECODE_W =  3'b001 ;
    defparam DPRAM16d_36b_0_0_0.GSR = "DISABLED" ;
    defparam DPRAM16d_36b_0_0_0.RESETMODE = "SYNC" ;
    defparam DPRAM16d_36b_0_0_0.REGMODE = "OUTREG" ;
    defparam DPRAM16d_36b_0_0_0.DATA_WIDTH_R = 36 ;
    defparam DPRAM16d_36b_0_0_0.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB DPRAM16d_36b_0_0_0 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), 
        .DI8(Data[8]), .DI9(Data[9]), .DI10(Data[10]), .DI11(Data[11]), 
        .DI12(Data[12]), .DI13(Data[13]), .DI14(Data[14]), .DI15(Data[15]), 
        .DI16(Data[16]), .DI17(Data[17]), .DI18(Data[18]), .DI19(Data[19]), 
        .DI20(Data[20]), .DI21(Data[21]), .DI22(Data[22]), .DI23(Data[23]), 
        .DI24(Data[24]), .DI25(Data[25]), .DI26(Data[26]), .DI27(Data[27]), 
        .DI28(Data[28]), .DI29(Data[29]), .DI30(Data[30]), .DI31(Data[31]), 
        .DI32(Data[32]), .DI33(Data[33]), .DI34(Data[34]), .DI35(Data[35]), 
        .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), .ADW3(WrAddress[3]), 
        .ADW4(scuba_vlo), .ADW5(scuba_vlo), .ADW6(scuba_vlo), .ADW7(scuba_vlo), 
        .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), .BE2(scuba_vhi), 
        .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), .CSW0(WE), .CSW1(scuba_vlo), 
        .CSW2(scuba_vlo), .ADR0(scuba_vlo), .ADR1(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR3(scuba_vlo), .ADR4(scuba_vlo), .ADR5(RdAddress[0]), .ADR6(RdAddress[1]), 
        .ADR7(RdAddress[2]), .ADR8(RdAddress[3]), .ADR9(scuba_vlo), .ADR10(scuba_vlo), 
        .ADR11(scuba_vlo), .ADR12(scuba_vlo), .ADR13(scuba_vlo), .CER(RdClockEn), 
        .CLKR(RdClock), .CSR0(scuba_vlo), .CSR1(scuba_vlo), .CSR2(scuba_vlo), 
        .RST(Reset), .DO0(Q[18]), .DO1(Q[19]), .DO2(Q[20]), .DO3(Q[21]), 
        .DO4(Q[22]), .DO5(Q[23]), .DO6(Q[24]), .DO7(Q[25]), .DO8(Q[26]), 
        .DO9(Q[27]), .DO10(Q[28]), .DO11(Q[29]), .DO12(Q[30]), .DO13(Q[31]), 
        .DO14(Q[32]), .DO15(Q[33]), .DO16(Q[34]), .DO17(Q[35]), .DO18(Q[0]), 
        .DO19(Q[1]), .DO20(Q[2]), .DO21(Q[3]), .DO22(Q[4]), .DO23(Q[5]), 
        .DO24(Q[6]), .DO25(Q[7]), .DO26(Q[8]), .DO27(Q[9]), .DO28(Q[10]), 
        .DO29(Q[11]), .DO30(Q[12]), .DO31(Q[13]), .DO32(Q[14]), .DO33(Q[15]), 
        .DO34(Q[16]), .DO35(Q[17]))
             /* synthesis MEM_LPC_FILE="DPRAM16d_36b.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="OUTREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;



    // exemplar begin
    // exemplar attribute DPRAM16d_36b_0_0_0 MEM_LPC_FILE DPRAM16d_36b.lpc
    // exemplar attribute DPRAM16d_36b_0_0_0 MEM_INIT_FILE 
    // exemplar attribute DPRAM16d_36b_0_0_0 CSDECODE_R 0b000
    // exemplar attribute DPRAM16d_36b_0_0_0 CSDECODE_W 0b001
    // exemplar attribute DPRAM16d_36b_0_0_0 GSR DISABLED
    // exemplar attribute DPRAM16d_36b_0_0_0 RESETMODE SYNC
    // exemplar attribute DPRAM16d_36b_0_0_0 REGMODE OUTREG
    // exemplar attribute DPRAM16d_36b_0_0_0 DATA_WIDTH_R 36
    // exemplar attribute DPRAM16d_36b_0_0_0 DATA_WIDTH_W 36
    // exemplar end

endmodule
