/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 4.0 */
/* D:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -n MULT_S16b_US18b -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type dspmult -widtha 16 -widthb 18 -widthp 34 -gsr ENABLED -area -signed -unsignedb -rego -regoclk CLK0 -regoce CE0 -regorst RST0 -clk0 -ce0 -rst0 -e  */
/* Mon Aug 22 19:53:15 2011 */


`timescale 1 ns / 1 ps
module MULT_S16b_US18b (CLK0, CE0, RST0, A, B, P);
    input wire CLK0;
    input wire CE0;
    input wire RST0;
    input wire [15:0] A;
    input wire [17:0] B;
    output wire [33:0] P;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam dsp_0.GSR = "ENABLED" ;
    defparam dsp_0.REG_SIGNEDB_RST = "RST0" ;
    defparam dsp_0.REG_SIGNEDB_CE = "CE0" ;
    defparam dsp_0.REG_SIGNEDB_CLK = "NONE" ;
    defparam dsp_0.REG_SIGNEDA_RST = "RST0" ;
    defparam dsp_0.REG_SIGNEDA_CE = "CE0" ;
    defparam dsp_0.REG_SIGNEDA_CLK = "NONE" ;
    defparam dsp_0.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_0.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_0.REG_OUTPUT_CLK = "CLK0" ;
    defparam dsp_0.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_0.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_0.REG_PIPELINE_CLK = "NONE" ;
    defparam dsp_0.REG_INPUTB_RST = "RST0" ;
    defparam dsp_0.REG_INPUTB_CE = "CE0" ;
    defparam dsp_0.REG_INPUTB_CLK = "NONE" ;
    defparam dsp_0.REG_INPUTA_RST = "RST0" ;
    defparam dsp_0.REG_INPUTA_CE = "CE0" ;
    defparam dsp_0.REG_INPUTA_CLK = "NONE" ;
    // synopsys translate_on
    MULT18X18B dsp_0 (.A17(A[15]), .A16(A[14]), .A15(A[13]), .A14(A[12]), 
        .A13(A[11]), .A12(A[10]), .A11(A[9]), .A10(A[8]), .A9(A[7]), .A8(A[6]), 
        .A7(A[5]), .A6(A[4]), .A5(A[3]), .A4(A[2]), .A3(A[1]), .A2(A[0]), 
        .A1(scuba_vlo), .A0(scuba_vlo), .B17(B[17]), .B16(B[16]), .B15(B[15]), 
        .B14(B[14]), .B13(B[13]), .B12(B[12]), .B11(B[11]), .B10(B[10]), 
        .B9(B[9]), .B8(B[8]), .B7(B[7]), .B6(B[6]), .B5(B[5]), .B4(B[4]), 
        .B3(B[3]), .B2(B[2]), .B1(B[1]), .B0(B[0]), .SIGNEDA(scuba_vhi), 
        .SIGNEDB(scuba_vlo), .SOURCEA(scuba_vlo), .SOURCEB(scuba_vlo), .CE0(CE0), 
        .CE1(scuba_vhi), .CE2(scuba_vhi), .CE3(scuba_vhi), .CLK0(CLK0), 
        .CLK1(scuba_vlo), .CLK2(scuba_vlo), .CLK3(scuba_vlo), .RST0(RST0), 
        .RST1(scuba_vlo), .RST2(scuba_vlo), .RST3(scuba_vlo), .SRIA17(scuba_vlo), 
        .SRIA16(scuba_vlo), .SRIA15(scuba_vlo), .SRIA14(scuba_vlo), .SRIA13(scuba_vlo), 
        .SRIA12(scuba_vlo), .SRIA11(scuba_vlo), .SRIA10(scuba_vlo), .SRIA9(scuba_vlo), 
        .SRIA8(scuba_vlo), .SRIA7(scuba_vlo), .SRIA6(scuba_vlo), .SRIA5(scuba_vlo), 
        .SRIA4(scuba_vlo), .SRIA3(scuba_vlo), .SRIA2(scuba_vlo), .SRIA1(scuba_vlo), 
        .SRIA0(scuba_vlo), .SRIB17(scuba_vlo), .SRIB16(scuba_vlo), .SRIB15(scuba_vlo), 
        .SRIB14(scuba_vlo), .SRIB13(scuba_vlo), .SRIB12(scuba_vlo), .SRIB11(scuba_vlo), 
        .SRIB10(scuba_vlo), .SRIB9(scuba_vlo), .SRIB8(scuba_vlo), .SRIB7(scuba_vlo), 
        .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), .SRIB4(scuba_vlo), .SRIB3(scuba_vlo), 
        .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), .SRIB0(scuba_vlo), .SROA17(), 
        .SROA16(), .SROA15(), .SROA14(), .SROA13(), .SROA12(), .SROA11(), 
        .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), .SROA5(), .SROA4(), 
        .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), .SROB16(), .SROB15(), 
        .SROB14(), .SROB13(), .SROB12(), .SROB11(), .SROB10(), .SROB9(), 
        .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), .SROB3(), .SROB2(), 
        .SROB1(), .SROB0(), .P35(P[33]), .P34(P[32]), .P33(P[31]), .P32(P[30]), 
        .P31(P[29]), .P30(P[28]), .P29(P[27]), .P28(P[26]), .P27(P[25]), 
        .P26(P[24]), .P25(P[23]), .P24(P[22]), .P23(P[21]), .P22(P[20]), 
        .P21(P[19]), .P20(P[18]), .P19(P[17]), .P18(P[16]), .P17(P[15]), 
        .P16(P[14]), .P15(P[13]), .P14(P[12]), .P13(P[11]), .P12(P[10]), 
        .P11(P[9]), .P10(P[8]), .P9(P[7]), .P8(P[6]), .P7(P[5]), .P6(P[4]), 
        .P5(P[3]), .P4(P[2]), .P3(P[1]), .P2(P[0]), .P1(), .P0())
             /* synthesis GSR="ENABLED" */
             /* synthesis REG_SIGNEDB_RST="RST0" */
             /* synthesis REG_SIGNEDB_CE="CE0" */
             /* synthesis REG_SIGNEDB_CLK="NONE" */
             /* synthesis REG_SIGNEDA_RST="RST0" */
             /* synthesis REG_SIGNEDA_CE="CE0" */
             /* synthesis REG_SIGNEDA_CLK="NONE" */
             /* synthesis REG_OUTPUT_RST="RST0" */
             /* synthesis REG_OUTPUT_CE="CE0" */
             /* synthesis REG_OUTPUT_CLK="CLK0" */
             /* synthesis REG_PIPELINE_RST="RST0" */
             /* synthesis REG_PIPELINE_CE="CE0" */
             /* synthesis REG_PIPELINE_CLK="NONE" */
             /* synthesis REG_INPUTB_RST="RST0" */
             /* synthesis REG_INPUTB_CE="CE0" */
             /* synthesis REG_INPUTB_CLK="NONE" */
             /* synthesis REG_INPUTA_RST="RST0" */
             /* synthesis REG_INPUTA_CE="CE0" */
             /* synthesis REG_INPUTA_CLK="NONE" */;



    // exemplar begin
    // exemplar attribute dsp_0 GSR ENABLED
    // exemplar attribute dsp_0 REG_SIGNEDB_RST RST0
    // exemplar attribute dsp_0 REG_SIGNEDB_CE CE0
    // exemplar attribute dsp_0 REG_SIGNEDB_CLK NONE
    // exemplar attribute dsp_0 REG_SIGNEDA_RST RST0
    // exemplar attribute dsp_0 REG_SIGNEDA_CE CE0
    // exemplar attribute dsp_0 REG_SIGNEDA_CLK NONE
    // exemplar attribute dsp_0 REG_OUTPUT_RST RST0
    // exemplar attribute dsp_0 REG_OUTPUT_CE CE0
    // exemplar attribute dsp_0 REG_OUTPUT_CLK CLK0
    // exemplar attribute dsp_0 REG_PIPELINE_RST RST0
    // exemplar attribute dsp_0 REG_PIPELINE_CE CE0
    // exemplar attribute dsp_0 REG_PIPELINE_CLK NONE
    // exemplar attribute dsp_0 REG_INPUTB_RST RST0
    // exemplar attribute dsp_0 REG_INPUTB_CE CE0
    // exemplar attribute dsp_0 REG_INPUTB_CLK NONE
    // exemplar attribute dsp_0 REG_INPUTA_RST RST0
    // exemplar attribute dsp_0 REG_INPUTA_CE CE0
    // exemplar attribute dsp_0 REG_INPUTA_CLK NONE
    // exemplar end

endmodule
