/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 6.1 */
/* C:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type bram -wp 10 -rp 0011 -rdata_width 18 -data_width 18 -num_rows 4096 -outdata REGISTERED -resetmode SYNC -cascade -1 -e  */
/* Wed Nov 30 17:36:36 2011 */


`timescale 1 ns / 1 ps
module RAM_DP_18b4096d (WrAddress, RdAddress, Data, WE, RdClock, 
    RdClockEn, Reset, WrClock, WrClockEn, Q);
    input wire [11:0] WrAddress;
    input wire [11:0] RdAddress;
    input wire [17:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [17:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;
    wire raddr11_ff;
    wire mdout1_1_0;
    wire mdout1_0_0;
    wire mdout1_1_1;
    wire mdout1_0_1;
    wire mdout1_1_2;
    wire mdout1_0_2;
    wire mdout1_1_3;
    wire mdout1_0_3;
    wire mdout1_1_4;
    wire mdout1_0_4;
    wire mdout1_1_5;
    wire mdout1_0_5;
    wire mdout1_1_6;
    wire mdout1_0_6;
    wire mdout1_1_7;
    wire mdout1_0_7;
    wire mdout1_1_8;
    wire mdout1_0_8;
    wire mdout1_1_9;
    wire mdout1_0_9;
    wire mdout1_1_10;
    wire mdout1_0_10;
    wire mdout1_1_11;
    wire mdout1_0_11;
    wire mdout1_1_12;
    wire mdout1_0_12;
    wire mdout1_1_13;
    wire mdout1_0_13;
    wire mdout1_1_14;
    wire mdout1_0_14;
    wire mdout1_1_15;
    wire mdout1_0_15;
    wire mdout1_1_16;
    wire mdout1_0_16;
    wire raddr11_ff2;
    wire mdout1_1_17;
    wire mdout1_0_17;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    // synopsys translate_off
    defparam RAM_DP_18b4096d_0_0_3.CSDECODE_B =  3'b000 ;
    defparam RAM_DP_18b4096d_0_0_3.CSDECODE_A =  3'b000 ;
    defparam RAM_DP_18b4096d_0_0_3.WRITEMODE_B = "NORMAL" ;
    defparam RAM_DP_18b4096d_0_0_3.WRITEMODE_A = "NORMAL" ;
    defparam RAM_DP_18b4096d_0_0_3.GSR = "DISABLED" ;
    defparam RAM_DP_18b4096d_0_0_3.RESETMODE = "SYNC" ;
    defparam RAM_DP_18b4096d_0_0_3.REGMODE_B = "OUTREG" ;
    defparam RAM_DP_18b4096d_0_0_3.REGMODE_A = "OUTREG" ;
    defparam RAM_DP_18b4096d_0_0_3.DATA_WIDTH_B = 9 ;
    defparam RAM_DP_18b4096d_0_0_3.DATA_WIDTH_A = 9 ;
    // synopsys translate_on
    DP16KB RAM_DP_18b4096d_0_0_3 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .WEA(WE), .CSA0(WrAddress[11]), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), .ADB4(RdAddress[1]), 
        .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), .ADB8(RdAddress[5]), 
        .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), .ADB11(RdAddress[8]), 
        .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), .CEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB0(RdAddress[11]), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_0_0), 
        .DOB1(mdout1_0_1), .DOB2(mdout1_0_2), .DOB3(mdout1_0_3), .DOB4(mdout1_0_4), 
        .DOB5(mdout1_0_5), .DOB6(mdout1_0_6), .DOB7(mdout1_0_7), .DOB8(mdout1_0_8), 
        .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), 
        .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="RAM_DP_18b4096d.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="9" */
             /* synthesis DATA_WIDTH_A="9" */;

    // synopsys translate_off
    defparam RAM_DP_18b4096d_0_1_2.CSDECODE_B =  3'b000 ;
    defparam RAM_DP_18b4096d_0_1_2.CSDECODE_A =  3'b000 ;
    defparam RAM_DP_18b4096d_0_1_2.WRITEMODE_B = "NORMAL" ;
    defparam RAM_DP_18b4096d_0_1_2.WRITEMODE_A = "NORMAL" ;
    defparam RAM_DP_18b4096d_0_1_2.GSR = "DISABLED" ;
    defparam RAM_DP_18b4096d_0_1_2.RESETMODE = "SYNC" ;
    defparam RAM_DP_18b4096d_0_1_2.REGMODE_B = "OUTREG" ;
    defparam RAM_DP_18b4096d_0_1_2.REGMODE_A = "OUTREG" ;
    defparam RAM_DP_18b4096d_0_1_2.DATA_WIDTH_B = 9 ;
    defparam RAM_DP_18b4096d_0_1_2.DATA_WIDTH_A = 9 ;
    // synopsys translate_on
    DP16KB RAM_DP_18b4096d_0_1_2 (.DIA0(Data[9]), .DIA1(Data[10]), .DIA2(Data[11]), 
        .DIA3(Data[12]), .DIA4(Data[13]), .DIA5(Data[14]), .DIA6(Data[15]), 
        .DIA7(Data[16]), .DIA8(Data[17]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .WEA(WE), .CSA0(WrAddress[11]), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), .ADB4(RdAddress[1]), 
        .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), .ADB8(RdAddress[5]), 
        .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), .ADB11(RdAddress[8]), 
        .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), .CEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB0(RdAddress[11]), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_0_9), 
        .DOB1(mdout1_0_10), .DOB2(mdout1_0_11), .DOB3(mdout1_0_12), .DOB4(mdout1_0_13), 
        .DOB5(mdout1_0_14), .DOB6(mdout1_0_15), .DOB7(mdout1_0_16), .DOB8(mdout1_0_17), 
        .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), 
        .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="RAM_DP_18b4096d.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="9" */
             /* synthesis DATA_WIDTH_A="9" */;

    // synopsys translate_off
    defparam RAM_DP_18b4096d_1_0_1.CSDECODE_B =  3'b001 ;
    defparam RAM_DP_18b4096d_1_0_1.CSDECODE_A =  3'b001 ;
    defparam RAM_DP_18b4096d_1_0_1.WRITEMODE_B = "NORMAL" ;
    defparam RAM_DP_18b4096d_1_0_1.WRITEMODE_A = "NORMAL" ;
    defparam RAM_DP_18b4096d_1_0_1.GSR = "DISABLED" ;
    defparam RAM_DP_18b4096d_1_0_1.RESETMODE = "SYNC" ;
    defparam RAM_DP_18b4096d_1_0_1.REGMODE_B = "OUTREG" ;
    defparam RAM_DP_18b4096d_1_0_1.REGMODE_A = "OUTREG" ;
    defparam RAM_DP_18b4096d_1_0_1.DATA_WIDTH_B = 9 ;
    defparam RAM_DP_18b4096d_1_0_1.DATA_WIDTH_A = 9 ;
    // synopsys translate_on
    DP16KB RAM_DP_18b4096d_1_0_1 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .WEA(WE), .CSA0(WrAddress[11]), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), .ADB4(RdAddress[1]), 
        .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), .ADB8(RdAddress[5]), 
        .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), .ADB11(RdAddress[8]), 
        .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), .CEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB0(RdAddress[11]), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_1_0), 
        .DOB1(mdout1_1_1), .DOB2(mdout1_1_2), .DOB3(mdout1_1_3), .DOB4(mdout1_1_4), 
        .DOB5(mdout1_1_5), .DOB6(mdout1_1_6), .DOB7(mdout1_1_7), .DOB8(mdout1_1_8), 
        .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), 
        .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="RAM_DP_18b4096d.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b001" */
             /* synthesis CSDECODE_A="0b001" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="9" */
             /* synthesis DATA_WIDTH_A="9" */;

    // synopsys translate_off
    defparam RAM_DP_18b4096d_1_1_0.CSDECODE_B =  3'b001 ;
    defparam RAM_DP_18b4096d_1_1_0.CSDECODE_A =  3'b001 ;
    defparam RAM_DP_18b4096d_1_1_0.WRITEMODE_B = "NORMAL" ;
    defparam RAM_DP_18b4096d_1_1_0.WRITEMODE_A = "NORMAL" ;
    defparam RAM_DP_18b4096d_1_1_0.GSR = "DISABLED" ;
    defparam RAM_DP_18b4096d_1_1_0.RESETMODE = "SYNC" ;
    defparam RAM_DP_18b4096d_1_1_0.REGMODE_B = "OUTREG" ;
    defparam RAM_DP_18b4096d_1_1_0.REGMODE_A = "OUTREG" ;
    defparam RAM_DP_18b4096d_1_1_0.DATA_WIDTH_B = 9 ;
    defparam RAM_DP_18b4096d_1_1_0.DATA_WIDTH_A = 9 ;
    // synopsys translate_on
    DP16KB RAM_DP_18b4096d_1_1_0 (.DIA0(Data[9]), .DIA1(Data[10]), .DIA2(Data[11]), 
        .DIA3(Data[12]), .DIA4(Data[13]), .DIA5(Data[14]), .DIA6(Data[15]), 
        .DIA7(Data[16]), .DIA8(Data[17]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .WEA(WE), .CSA0(WrAddress[11]), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), .ADB4(RdAddress[1]), 
        .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), .ADB8(RdAddress[5]), 
        .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), .ADB11(RdAddress[8]), 
        .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), .CEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB0(RdAddress[11]), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_1_9), 
        .DOB1(mdout1_1_10), .DOB2(mdout1_1_11), .DOB3(mdout1_1_12), .DOB4(mdout1_1_13), 
        .DOB5(mdout1_1_14), .DOB6(mdout1_1_15), .DOB7(mdout1_1_16), .DOB8(mdout1_1_17), 
        .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), 
        .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="RAM_DP_18b4096d.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b001" */
             /* synthesis CSDECODE_A="0b001" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="9" */
             /* synthesis DATA_WIDTH_A="9" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(RdAddress[11]), .SP(RdClockEn), .CK(RdClock), .CD(scuba_vlo), 
        .Q(raddr11_ff))
             /* synthesis GSR="ENABLED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(raddr11_ff), .SP(RdClockEn), .CK(RdClock), .CD(scuba_vlo), 
        .Q(raddr11_ff2))
             /* synthesis GSR="ENABLED" */;

    MUX21 mux_17 (.D0(mdout1_0_0), .D1(mdout1_1_0), .SD(raddr11_ff2), .Z(Q[0]));

    MUX21 mux_16 (.D0(mdout1_0_1), .D1(mdout1_1_1), .SD(raddr11_ff2), .Z(Q[1]));

    MUX21 mux_15 (.D0(mdout1_0_2), .D1(mdout1_1_2), .SD(raddr11_ff2), .Z(Q[2]));

    MUX21 mux_14 (.D0(mdout1_0_3), .D1(mdout1_1_3), .SD(raddr11_ff2), .Z(Q[3]));

    MUX21 mux_13 (.D0(mdout1_0_4), .D1(mdout1_1_4), .SD(raddr11_ff2), .Z(Q[4]));

    MUX21 mux_12 (.D0(mdout1_0_5), .D1(mdout1_1_5), .SD(raddr11_ff2), .Z(Q[5]));

    MUX21 mux_11 (.D0(mdout1_0_6), .D1(mdout1_1_6), .SD(raddr11_ff2), .Z(Q[6]));

    MUX21 mux_10 (.D0(mdout1_0_7), .D1(mdout1_1_7), .SD(raddr11_ff2), .Z(Q[7]));

    MUX21 mux_9 (.D0(mdout1_0_8), .D1(mdout1_1_8), .SD(raddr11_ff2), .Z(Q[8]));

    MUX21 mux_8 (.D0(mdout1_0_9), .D1(mdout1_1_9), .SD(raddr11_ff2), .Z(Q[9]));

    MUX21 mux_7 (.D0(mdout1_0_10), .D1(mdout1_1_10), .SD(raddr11_ff2), .Z(Q[10]));

    MUX21 mux_6 (.D0(mdout1_0_11), .D1(mdout1_1_11), .SD(raddr11_ff2), .Z(Q[11]));

    MUX21 mux_5 (.D0(mdout1_0_12), .D1(mdout1_1_12), .SD(raddr11_ff2), .Z(Q[12]));

    MUX21 mux_4 (.D0(mdout1_0_13), .D1(mdout1_1_13), .SD(raddr11_ff2), .Z(Q[13]));

    MUX21 mux_3 (.D0(mdout1_0_14), .D1(mdout1_1_14), .SD(raddr11_ff2), .Z(Q[14]));

    MUX21 mux_2 (.D0(mdout1_0_15), .D1(mdout1_1_15), .SD(raddr11_ff2), .Z(Q[15]));

    MUX21 mux_1 (.D0(mdout1_0_16), .D1(mdout1_1_16), .SD(raddr11_ff2), .Z(Q[16]));

    MUX21 mux_0 (.D0(mdout1_0_17), .D1(mdout1_1_17), .SD(raddr11_ff2), .Z(Q[17]));



    // exemplar begin
    // exemplar attribute RAM_DP_18b4096d_0_0_3 MEM_LPC_FILE RAM_DP_18b4096d.lpc
    // exemplar attribute RAM_DP_18b4096d_0_0_3 MEM_INIT_FILE 
    // exemplar attribute RAM_DP_18b4096d_0_0_3 CSDECODE_B 0b000
    // exemplar attribute RAM_DP_18b4096d_0_0_3 CSDECODE_A 0b000
    // exemplar attribute RAM_DP_18b4096d_0_0_3 WRITEMODE_B NORMAL
    // exemplar attribute RAM_DP_18b4096d_0_0_3 WRITEMODE_A NORMAL
    // exemplar attribute RAM_DP_18b4096d_0_0_3 GSR DISABLED
    // exemplar attribute RAM_DP_18b4096d_0_0_3 RESETMODE SYNC
    // exemplar attribute RAM_DP_18b4096d_0_0_3 REGMODE_B OUTREG
    // exemplar attribute RAM_DP_18b4096d_0_0_3 REGMODE_A OUTREG
    // exemplar attribute RAM_DP_18b4096d_0_0_3 DATA_WIDTH_B 9
    // exemplar attribute RAM_DP_18b4096d_0_0_3 DATA_WIDTH_A 9
    // exemplar attribute RAM_DP_18b4096d_0_1_2 MEM_LPC_FILE RAM_DP_18b4096d.lpc
    // exemplar attribute RAM_DP_18b4096d_0_1_2 MEM_INIT_FILE 
    // exemplar attribute RAM_DP_18b4096d_0_1_2 CSDECODE_B 0b000
    // exemplar attribute RAM_DP_18b4096d_0_1_2 CSDECODE_A 0b000
    // exemplar attribute RAM_DP_18b4096d_0_1_2 WRITEMODE_B NORMAL
    // exemplar attribute RAM_DP_18b4096d_0_1_2 WRITEMODE_A NORMAL
    // exemplar attribute RAM_DP_18b4096d_0_1_2 GSR DISABLED
    // exemplar attribute RAM_DP_18b4096d_0_1_2 RESETMODE SYNC
    // exemplar attribute RAM_DP_18b4096d_0_1_2 REGMODE_B OUTREG
    // exemplar attribute RAM_DP_18b4096d_0_1_2 REGMODE_A OUTREG
    // exemplar attribute RAM_DP_18b4096d_0_1_2 DATA_WIDTH_B 9
    // exemplar attribute RAM_DP_18b4096d_0_1_2 DATA_WIDTH_A 9
    // exemplar attribute RAM_DP_18b4096d_1_0_1 MEM_LPC_FILE RAM_DP_18b4096d.lpc
    // exemplar attribute RAM_DP_18b4096d_1_0_1 MEM_INIT_FILE 
    // exemplar attribute RAM_DP_18b4096d_1_0_1 CSDECODE_B 0b001
    // exemplar attribute RAM_DP_18b4096d_1_0_1 CSDECODE_A 0b001
    // exemplar attribute RAM_DP_18b4096d_1_0_1 WRITEMODE_B NORMAL
    // exemplar attribute RAM_DP_18b4096d_1_0_1 WRITEMODE_A NORMAL
    // exemplar attribute RAM_DP_18b4096d_1_0_1 GSR DISABLED
    // exemplar attribute RAM_DP_18b4096d_1_0_1 RESETMODE SYNC
    // exemplar attribute RAM_DP_18b4096d_1_0_1 REGMODE_B OUTREG
    // exemplar attribute RAM_DP_18b4096d_1_0_1 REGMODE_A OUTREG
    // exemplar attribute RAM_DP_18b4096d_1_0_1 DATA_WIDTH_B 9
    // exemplar attribute RAM_DP_18b4096d_1_0_1 DATA_WIDTH_A 9
    // exemplar attribute RAM_DP_18b4096d_1_1_0 MEM_LPC_FILE RAM_DP_18b4096d.lpc
    // exemplar attribute RAM_DP_18b4096d_1_1_0 MEM_INIT_FILE 
    // exemplar attribute RAM_DP_18b4096d_1_1_0 CSDECODE_B 0b001
    // exemplar attribute RAM_DP_18b4096d_1_1_0 CSDECODE_A 0b001
    // exemplar attribute RAM_DP_18b4096d_1_1_0 WRITEMODE_B NORMAL
    // exemplar attribute RAM_DP_18b4096d_1_1_0 WRITEMODE_A NORMAL
    // exemplar attribute RAM_DP_18b4096d_1_1_0 GSR DISABLED
    // exemplar attribute RAM_DP_18b4096d_1_1_0 RESETMODE SYNC
    // exemplar attribute RAM_DP_18b4096d_1_1_0 REGMODE_B OUTREG
    // exemplar attribute RAM_DP_18b4096d_1_1_0 REGMODE_A OUTREG
    // exemplar attribute RAM_DP_18b4096d_1_1_0 DATA_WIDTH_B 9
    // exemplar attribute RAM_DP_18b4096d_1_1_0 DATA_WIDTH_A 9
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
