/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 6.1 */
/* D:\lscc\diamond\1.2\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type bram -wp 10 -rp 0011 -rdata_width 16 -data_width 16 -num_rows 4096 -outdata REGISTERED -resetmode SYNC -cascade -1 -e  */
/* Wed Jul 27 11:23:58 2011 */


`timescale 1 ns / 1 ps
module RAMDP_16_4096 (WrAddress, RdAddress, Data, WE, RdClock, RdClockEn, 
    Reset, WrClock, WrClockEn, Q);
    input wire [11:0] WrAddress;
    input wire [11:0] RdAddress;
    input wire [15:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [15:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    // synopsys translate_off
    defparam RAMDP_16_4096_0_0_3.CSDECODE_B =  3'b000 ;
    defparam RAMDP_16_4096_0_0_3.CSDECODE_A =  3'b000 ;
    defparam RAMDP_16_4096_0_0_3.WRITEMODE_B = "NORMAL" ;
    defparam RAMDP_16_4096_0_0_3.WRITEMODE_A = "NORMAL" ;
    defparam RAMDP_16_4096_0_0_3.GSR = "DISABLED" ;
    defparam RAMDP_16_4096_0_0_3.RESETMODE = "SYNC" ;
    defparam RAMDP_16_4096_0_0_3.REGMODE_B = "OUTREG" ;
    defparam RAMDP_16_4096_0_0_3.REGMODE_A = "OUTREG" ;
    defparam RAMDP_16_4096_0_0_3.DATA_WIDTH_B = 4 ;
    defparam RAMDP_16_4096_0_0_3.DATA_WIDTH_A = 4 ;
    // synopsys translate_on
    DP16KB RAMDP_16_4096_0_0_3 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(WrAddress[0]), .ADA3(WrAddress[1]), .ADA4(WrAddress[2]), 
        .ADA5(WrAddress[3]), .ADA6(WrAddress[4]), .ADA7(WrAddress[5]), .ADA8(WrAddress[6]), 
        .ADA9(WrAddress[7]), .ADA10(WrAddress[8]), .ADA11(WrAddress[9]), 
        .ADA12(WrAddress[10]), .ADA13(WrAddress[11]), .CEA(WrClockEn), .CLKA(WrClock), 
        .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(RdAddress[0]), .ADB3(RdAddress[1]), .ADB4(RdAddress[2]), 
        .ADB5(RdAddress[3]), .ADB6(RdAddress[4]), .ADB7(RdAddress[5]), .ADB8(RdAddress[6]), 
        .ADB9(RdAddress[7]), .ADB10(RdAddress[8]), .ADB11(RdAddress[9]), 
        .ADB12(RdAddress[10]), .ADB13(RdAddress[11]), .CEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[0]), .DOB1(Q[1]), 
        .DOB2(Q[2]), .DOB3(Q[3]), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), 
        .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), 
        .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="RAMDP_16_4096.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="4" */
             /* synthesis DATA_WIDTH_A="4" */;

    // synopsys translate_off
    defparam RAMDP_16_4096_0_1_2.CSDECODE_B =  3'b000 ;
    defparam RAMDP_16_4096_0_1_2.CSDECODE_A =  3'b000 ;
    defparam RAMDP_16_4096_0_1_2.WRITEMODE_B = "NORMAL" ;
    defparam RAMDP_16_4096_0_1_2.WRITEMODE_A = "NORMAL" ;
    defparam RAMDP_16_4096_0_1_2.GSR = "DISABLED" ;
    defparam RAMDP_16_4096_0_1_2.RESETMODE = "SYNC" ;
    defparam RAMDP_16_4096_0_1_2.REGMODE_B = "OUTREG" ;
    defparam RAMDP_16_4096_0_1_2.REGMODE_A = "OUTREG" ;
    defparam RAMDP_16_4096_0_1_2.DATA_WIDTH_B = 4 ;
    defparam RAMDP_16_4096_0_1_2.DATA_WIDTH_A = 4 ;
    // synopsys translate_on
    DP16KB RAMDP_16_4096_0_1_2 (.DIA0(Data[4]), .DIA1(Data[5]), .DIA2(Data[6]), 
        .DIA3(Data[7]), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(WrAddress[0]), .ADA3(WrAddress[1]), .ADA4(WrAddress[2]), 
        .ADA5(WrAddress[3]), .ADA6(WrAddress[4]), .ADA7(WrAddress[5]), .ADA8(WrAddress[6]), 
        .ADA9(WrAddress[7]), .ADA10(WrAddress[8]), .ADA11(WrAddress[9]), 
        .ADA12(WrAddress[10]), .ADA13(WrAddress[11]), .CEA(WrClockEn), .CLKA(WrClock), 
        .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(RdAddress[0]), .ADB3(RdAddress[1]), .ADB4(RdAddress[2]), 
        .ADB5(RdAddress[3]), .ADB6(RdAddress[4]), .ADB7(RdAddress[5]), .ADB8(RdAddress[6]), 
        .ADB9(RdAddress[7]), .ADB10(RdAddress[8]), .ADB11(RdAddress[9]), 
        .ADB12(RdAddress[10]), .ADB13(RdAddress[11]), .CEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[4]), .DOB1(Q[5]), 
        .DOB2(Q[6]), .DOB3(Q[7]), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), 
        .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), 
        .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="RAMDP_16_4096.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="4" */
             /* synthesis DATA_WIDTH_A="4" */;

    // synopsys translate_off
    defparam RAMDP_16_4096_0_2_1.CSDECODE_B =  3'b000 ;
    defparam RAMDP_16_4096_0_2_1.CSDECODE_A =  3'b000 ;
    defparam RAMDP_16_4096_0_2_1.WRITEMODE_B = "NORMAL" ;
    defparam RAMDP_16_4096_0_2_1.WRITEMODE_A = "NORMAL" ;
    defparam RAMDP_16_4096_0_2_1.GSR = "DISABLED" ;
    defparam RAMDP_16_4096_0_2_1.RESETMODE = "SYNC" ;
    defparam RAMDP_16_4096_0_2_1.REGMODE_B = "OUTREG" ;
    defparam RAMDP_16_4096_0_2_1.REGMODE_A = "OUTREG" ;
    defparam RAMDP_16_4096_0_2_1.DATA_WIDTH_B = 4 ;
    defparam RAMDP_16_4096_0_2_1.DATA_WIDTH_A = 4 ;
    // synopsys translate_on
    DP16KB RAMDP_16_4096_0_2_1 (.DIA0(Data[8]), .DIA1(Data[9]), .DIA2(Data[10]), 
        .DIA3(Data[11]), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(WrAddress[0]), .ADA3(WrAddress[1]), .ADA4(WrAddress[2]), 
        .ADA5(WrAddress[3]), .ADA6(WrAddress[4]), .ADA7(WrAddress[5]), .ADA8(WrAddress[6]), 
        .ADA9(WrAddress[7]), .ADA10(WrAddress[8]), .ADA11(WrAddress[9]), 
        .ADA12(WrAddress[10]), .ADA13(WrAddress[11]), .CEA(WrClockEn), .CLKA(WrClock), 
        .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(RdAddress[0]), .ADB3(RdAddress[1]), .ADB4(RdAddress[2]), 
        .ADB5(RdAddress[3]), .ADB6(RdAddress[4]), .ADB7(RdAddress[5]), .ADB8(RdAddress[6]), 
        .ADB9(RdAddress[7]), .ADB10(RdAddress[8]), .ADB11(RdAddress[9]), 
        .ADB12(RdAddress[10]), .ADB13(RdAddress[11]), .CEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[8]), .DOB1(Q[9]), 
        .DOB2(Q[10]), .DOB3(Q[11]), .DOB4(), .DOB5(), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="RAMDP_16_4096.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="4" */
             /* synthesis DATA_WIDTH_A="4" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam RAMDP_16_4096_0_3_0.CSDECODE_B =  3'b000 ;
    defparam RAMDP_16_4096_0_3_0.CSDECODE_A =  3'b000 ;
    defparam RAMDP_16_4096_0_3_0.WRITEMODE_B = "NORMAL" ;
    defparam RAMDP_16_4096_0_3_0.WRITEMODE_A = "NORMAL" ;
    defparam RAMDP_16_4096_0_3_0.GSR = "DISABLED" ;
    defparam RAMDP_16_4096_0_3_0.RESETMODE = "SYNC" ;
    defparam RAMDP_16_4096_0_3_0.REGMODE_B = "OUTREG" ;
    defparam RAMDP_16_4096_0_3_0.REGMODE_A = "OUTREG" ;
    defparam RAMDP_16_4096_0_3_0.DATA_WIDTH_B = 4 ;
    defparam RAMDP_16_4096_0_3_0.DATA_WIDTH_A = 4 ;
    // synopsys translate_on
    DP16KB RAMDP_16_4096_0_3_0 (.DIA0(Data[12]), .DIA1(Data[13]), .DIA2(Data[14]), 
        .DIA3(Data[15]), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(WrAddress[0]), .ADA3(WrAddress[1]), .ADA4(WrAddress[2]), 
        .ADA5(WrAddress[3]), .ADA6(WrAddress[4]), .ADA7(WrAddress[5]), .ADA8(WrAddress[6]), 
        .ADA9(WrAddress[7]), .ADA10(WrAddress[8]), .ADA11(WrAddress[9]), 
        .ADA12(WrAddress[10]), .ADA13(WrAddress[11]), .CEA(WrClockEn), .CLKA(WrClock), 
        .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(RdAddress[0]), .ADB3(RdAddress[1]), .ADB4(RdAddress[2]), 
        .ADB5(RdAddress[3]), .ADB6(RdAddress[4]), .ADB7(RdAddress[5]), .ADB8(RdAddress[6]), 
        .ADB9(RdAddress[7]), .ADB10(RdAddress[8]), .ADB11(RdAddress[9]), 
        .ADB12(RdAddress[10]), .ADB13(RdAddress[11]), .CEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[12]), 
        .DOB1(Q[13]), .DOB2(Q[14]), .DOB3(Q[15]), .DOB4(), .DOB5(), .DOB6(), 
        .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), 
        .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="RAMDP_16_4096.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="4" */
             /* synthesis DATA_WIDTH_A="4" */;



    // exemplar begin
    // exemplar attribute RAMDP_16_4096_0_0_3 MEM_LPC_FILE RAMDP_16_4096.lpc
    // exemplar attribute RAMDP_16_4096_0_0_3 MEM_INIT_FILE 
    // exemplar attribute RAMDP_16_4096_0_0_3 CSDECODE_B 0b000
    // exemplar attribute RAMDP_16_4096_0_0_3 CSDECODE_A 0b000
    // exemplar attribute RAMDP_16_4096_0_0_3 WRITEMODE_B NORMAL
    // exemplar attribute RAMDP_16_4096_0_0_3 WRITEMODE_A NORMAL
    // exemplar attribute RAMDP_16_4096_0_0_3 GSR DISABLED
    // exemplar attribute RAMDP_16_4096_0_0_3 RESETMODE SYNC
    // exemplar attribute RAMDP_16_4096_0_0_3 REGMODE_B OUTREG
    // exemplar attribute RAMDP_16_4096_0_0_3 REGMODE_A OUTREG
    // exemplar attribute RAMDP_16_4096_0_0_3 DATA_WIDTH_B 4
    // exemplar attribute RAMDP_16_4096_0_0_3 DATA_WIDTH_A 4
    // exemplar attribute RAMDP_16_4096_0_1_2 MEM_LPC_FILE RAMDP_16_4096.lpc
    // exemplar attribute RAMDP_16_4096_0_1_2 MEM_INIT_FILE 
    // exemplar attribute RAMDP_16_4096_0_1_2 CSDECODE_B 0b000
    // exemplar attribute RAMDP_16_4096_0_1_2 CSDECODE_A 0b000
    // exemplar attribute RAMDP_16_4096_0_1_2 WRITEMODE_B NORMAL
    // exemplar attribute RAMDP_16_4096_0_1_2 WRITEMODE_A NORMAL
    // exemplar attribute RAMDP_16_4096_0_1_2 GSR DISABLED
    // exemplar attribute RAMDP_16_4096_0_1_2 RESETMODE SYNC
    // exemplar attribute RAMDP_16_4096_0_1_2 REGMODE_B OUTREG
    // exemplar attribute RAMDP_16_4096_0_1_2 REGMODE_A OUTREG
    // exemplar attribute RAMDP_16_4096_0_1_2 DATA_WIDTH_B 4
    // exemplar attribute RAMDP_16_4096_0_1_2 DATA_WIDTH_A 4
    // exemplar attribute RAMDP_16_4096_0_2_1 MEM_LPC_FILE RAMDP_16_4096.lpc
    // exemplar attribute RAMDP_16_4096_0_2_1 MEM_INIT_FILE 
    // exemplar attribute RAMDP_16_4096_0_2_1 CSDECODE_B 0b000
    // exemplar attribute RAMDP_16_4096_0_2_1 CSDECODE_A 0b000
    // exemplar attribute RAMDP_16_4096_0_2_1 WRITEMODE_B NORMAL
    // exemplar attribute RAMDP_16_4096_0_2_1 WRITEMODE_A NORMAL
    // exemplar attribute RAMDP_16_4096_0_2_1 GSR DISABLED
    // exemplar attribute RAMDP_16_4096_0_2_1 RESETMODE SYNC
    // exemplar attribute RAMDP_16_4096_0_2_1 REGMODE_B OUTREG
    // exemplar attribute RAMDP_16_4096_0_2_1 REGMODE_A OUTREG
    // exemplar attribute RAMDP_16_4096_0_2_1 DATA_WIDTH_B 4
    // exemplar attribute RAMDP_16_4096_0_2_1 DATA_WIDTH_A 4
    // exemplar attribute RAMDP_16_4096_0_3_0 MEM_LPC_FILE RAMDP_16_4096.lpc
    // exemplar attribute RAMDP_16_4096_0_3_0 MEM_INIT_FILE 
    // exemplar attribute RAMDP_16_4096_0_3_0 CSDECODE_B 0b000
    // exemplar attribute RAMDP_16_4096_0_3_0 CSDECODE_A 0b000
    // exemplar attribute RAMDP_16_4096_0_3_0 WRITEMODE_B NORMAL
    // exemplar attribute RAMDP_16_4096_0_3_0 WRITEMODE_A NORMAL
    // exemplar attribute RAMDP_16_4096_0_3_0 GSR DISABLED
    // exemplar attribute RAMDP_16_4096_0_3_0 RESETMODE SYNC
    // exemplar attribute RAMDP_16_4096_0_3_0 REGMODE_B OUTREG
    // exemplar attribute RAMDP_16_4096_0_3_0 REGMODE_A OUTREG
    // exemplar attribute RAMDP_16_4096_0_3_0 DATA_WIDTH_B 4
    // exemplar attribute RAMDP_16_4096_0_3_0 DATA_WIDTH_A 4
    // exemplar end

endmodule
